// Generated by tools/generate_other_assets_jsfl.py. Do not edit by hand.
// Open this file with Adobe Animate to export non-character SVG assets.
// Output lands directly in vector-art/svg/.
// macOS direct run:
// "/Applications/Adobe Animate 2024/Adobe Animate 2024.app/Contents/MacOS/Adobe Animate 2024" vector-art/export-other-assets-svg.jsfl

var SOURCE_FLA_URI = "file:///Users/jacobgrahn/Documents/platform-racing-2-client/flash/platform-racing-2.fla";
var ADOBE_SVG_EXPORTER_URI = "file:///Applications/Adobe%20Animate%202024/Adobe%20Animate%202024.app/Contents/Common/Configuration/Extensions/ExportSVG/jsfl/Export%20SVG.jsfl";
var JOBS = [
  {
    "category": "backgrounds",
    "exportPath": "backgrounds/bg1.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/backgrounds/bg1.svg",
    "slug": "bg1",
    "symbolName": "UI/Pages/Levels/Backgrounds/bg1"
  },
  {
    "category": "backgrounds",
    "exportPath": "backgrounds/bg2.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/backgrounds/bg2.svg",
    "slug": "bg2",
    "symbolName": "UI/Pages/Levels/Backgrounds/bg2"
  },
  {
    "category": "backgrounds",
    "exportPath": "backgrounds/bg3.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/backgrounds/bg3.svg",
    "slug": "bg3",
    "symbolName": "UI/Pages/Levels/Backgrounds/bg3"
  },
  {
    "category": "backgrounds",
    "exportPath": "backgrounds/bg4.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/backgrounds/bg4.svg",
    "slug": "bg4",
    "symbolName": "UI/Pages/Levels/Backgrounds/bg4"
  },
  {
    "category": "backgrounds",
    "exportPath": "backgrounds/bg5.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/backgrounds/bg5.svg",
    "slug": "bg5",
    "symbolName": "UI/Pages/Levels/Backgrounds/bg5"
  },
  {
    "category": "backgrounds",
    "exportPath": "backgrounds/bg6.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/backgrounds/bg6.svg",
    "slug": "bg6",
    "symbolName": "UI/Pages/Levels/Backgrounds/bg6"
  },
  {
    "category": "backgrounds",
    "exportPath": "backgrounds/bg7.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/backgrounds/bg7.svg",
    "slug": "bg7",
    "symbolName": "UI/Pages/Levels/Backgrounds/bg7"
  },
  {
    "category": "stamps",
    "exportPath": "stamps/petrified_tree.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/stamps/petrified_tree.svg",
    "slug": "petrified_tree",
    "symbolName": "UI/Pages/Levels/Stamps/PetrifiedTree"
  },
  {
    "category": "stamps",
    "exportPath": "stamps/rock1.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/stamps/rock1.svg",
    "slug": "rock1",
    "symbolName": "UI/Pages/Levels/Stamps/rock1"
  },
  {
    "category": "stamps",
    "exportPath": "stamps/rock2.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/stamps/rock2.svg",
    "slug": "rock2",
    "symbolName": "UI/Pages/Levels/Stamps/rock2"
  },
  {
    "category": "stamps",
    "exportPath": "stamps/spire1.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/stamps/spire1.svg",
    "slug": "spire1",
    "symbolName": "UI/Pages/Levels/Stamps/spire1"
  },
  {
    "category": "stamps",
    "exportPath": "stamps/spire2.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/stamps/spire2.svg",
    "slug": "spire2",
    "symbolName": "UI/Pages/Levels/Stamps/spire2"
  },
  {
    "category": "stamps",
    "exportPath": "stamps/tree1.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/stamps/tree1.svg",
    "slug": "tree1",
    "symbolName": "UI/Pages/Levels/Stamps/tree1"
  },
  {
    "category": "stamps",
    "exportPath": "stamps/tree2.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/stamps/tree2.svg",
    "slug": "tree2",
    "symbolName": "UI/Pages/Levels/Stamps/tree2"
  },
  {
    "category": "stamps",
    "exportPath": "stamps/tree3.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/stamps/tree3.svg",
    "slug": "tree3",
    "symbolName": "UI/Pages/Levels/Stamps/tree3"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_00.svg",
    "frame": 0,
    "frameIndex": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_00.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_01.svg",
    "frame": 1,
    "frameIndex": 1,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_01.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_02.svg",
    "frame": 2,
    "frameIndex": 2,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_02.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_03.svg",
    "frame": 3,
    "frameIndex": 3,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_03.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_04.svg",
    "frame": 4,
    "frameIndex": 4,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_04.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_05.svg",
    "frame": 5,
    "frameIndex": 5,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_05.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_06.svg",
    "frame": 6,
    "frameIndex": 6,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_06.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_07.svg",
    "frame": 7,
    "frameIndex": 7,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_07.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_08.svg",
    "frame": 8,
    "frameIndex": 8,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_08.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_09.svg",
    "frame": 9,
    "frameIndex": 9,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_09.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_10.svg",
    "frame": 10,
    "frameIndex": 10,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_10.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_11.svg",
    "frame": 11,
    "frameIndex": 11,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_11.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_12.svg",
    "frame": 12,
    "frameIndex": 12,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_12.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_13.svg",
    "frame": 13,
    "frameIndex": 13,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_13.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_14.svg",
    "frame": 14,
    "frameIndex": 14,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_14.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_15.svg",
    "frame": 15,
    "frameIndex": 15,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_15.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_16.svg",
    "frame": 16,
    "frameIndex": 16,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_16.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot/frame_17.svg",
    "frame": 17,
    "frameIndex": 17,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot/frame_17.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/lightning_bolt/frame_00.svg",
    "frame": 0,
    "frameIndex": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/lightning_bolt/frame_00.svg",
    "slug": "lightning_bolt",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LightningBolt"
  },
  {
    "category": "effects",
    "exportPath": "effects/slash/frame_00.svg",
    "frame": 0,
    "frameIndex": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/slash/frame_00.svg",
    "slug": "slash",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Slash"
  },
  {
    "category": "effects",
    "exportPath": "effects/slash/frame_01.svg",
    "frame": 1,
    "frameIndex": 1,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/slash/frame_01.svg",
    "slug": "slash",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Slash"
  },
  {
    "category": "effects",
    "exportPath": "effects/slash/frame_02.svg",
    "frame": 2,
    "frameIndex": 2,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/slash/frame_02.svg",
    "slug": "slash",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Slash"
  },
  {
    "category": "effects",
    "exportPath": "effects/slash/frame_03.svg",
    "frame": 3,
    "frameIndex": 3,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/slash/frame_03.svg",
    "slug": "slash",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Slash"
  },
  {
    "category": "effects",
    "exportPath": "effects/slash/frame_04.svg",
    "frame": 4,
    "frameIndex": 4,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/slash/frame_04.svg",
    "slug": "slash",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Slash"
  },
  {
    "category": "effects",
    "exportPath": "effects/slash/frame_05.svg",
    "frame": 5,
    "frameIndex": 5,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/slash/frame_05.svg",
    "slug": "slash",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Slash"
  },
  {
    "category": "effects",
    "exportPath": "effects/sting/frame_00.svg",
    "frame": 0,
    "frameIndex": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/sting/frame_00.svg",
    "slug": "sting",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Sting"
  },
  {
    "category": "effects",
    "exportPath": "effects/teleport/frame_00.svg",
    "frame": 0,
    "frameIndex": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/teleport/frame_00.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Teleport"
  },
  {
    "category": "effects",
    "exportPath": "effects/teleport/frame_01.svg",
    "frame": 1,
    "frameIndex": 1,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/teleport/frame_01.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Teleport"
  },
  {
    "category": "effects",
    "exportPath": "effects/teleport/frame_02.svg",
    "frame": 2,
    "frameIndex": 2,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/teleport/frame_02.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Teleport"
  },
  {
    "category": "effects",
    "exportPath": "effects/teleport/frame_03.svg",
    "frame": 3,
    "frameIndex": 3,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/teleport/frame_03.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Teleport"
  },
  {
    "category": "effects",
    "exportPath": "effects/teleport/frame_04.svg",
    "frame": 4,
    "frameIndex": 4,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/teleport/frame_04.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Teleport"
  },
  {
    "category": "effects",
    "exportPath": "effects/teleport/frame_05.svg",
    "frame": 5,
    "frameIndex": 5,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/teleport/frame_05.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Teleport"
  },
  {
    "category": "effects",
    "exportPath": "effects/teleport/frame_06.svg",
    "frame": 6,
    "frameIndex": 6,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/teleport/frame_06.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Teleport"
  },
  {
    "category": "effects",
    "exportPath": "effects/teleport/frame_07.svg",
    "frame": 7,
    "frameIndex": 7,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/teleport/frame_07.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Teleport"
  },
  {
    "category": "effects",
    "exportPath": "effects/teleport/frame_08.svg",
    "frame": 8,
    "frameIndex": 8,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/teleport/frame_08.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Teleport"
  },
  {
    "category": "effects",
    "exportPath": "effects/teleport/frame_09.svg",
    "frame": 9,
    "frameIndex": 9,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/teleport/frame_09.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Teleport"
  },
  {
    "category": "effects",
    "exportPath": "effects/teleport/frame_10.svg",
    "frame": 10,
    "frameIndex": 10,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/teleport/frame_10.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Teleport"
  },
  {
    "category": "effects",
    "exportPath": "effects/teleport/frame_11.svg",
    "frame": 11,
    "frameIndex": 11,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/teleport/frame_11.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Teleport"
  },
  {
    "category": "effects",
    "exportPath": "effects/teleport/frame_12.svg",
    "frame": 12,
    "frameIndex": 12,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/teleport/frame_12.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Teleport"
  },
  {
    "category": "effects",
    "exportPath": "effects/teleport/frame_13.svg",
    "frame": 13,
    "frameIndex": 13,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/teleport/frame_13.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Teleport"
  },
  {
    "category": "effects",
    "exportPath": "effects/teleport/frame_14.svg",
    "frame": 14,
    "frameIndex": 14,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/teleport/frame_14.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Teleport"
  },
  {
    "category": "effects",
    "exportPath": "effects/teleport/frame_15.svg",
    "frame": 15,
    "frameIndex": 15,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/teleport/frame_15.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Teleport"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst/frame_00.svg",
    "frame": 0,
    "frameIndex": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst/frame_00.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurst"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst/frame_01.svg",
    "frame": 1,
    "frameIndex": 1,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst/frame_01.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurst"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst/frame_02.svg",
    "frame": 2,
    "frameIndex": 2,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst/frame_02.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurst"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst/frame_03.svg",
    "frame": 3,
    "frameIndex": 3,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst/frame_03.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurst"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst/frame_04.svg",
    "frame": 4,
    "frameIndex": 4,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst/frame_04.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurst"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst/frame_05.svg",
    "frame": 5,
    "frameIndex": 5,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst/frame_05.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurst"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst/frame_06.svg",
    "frame": 6,
    "frameIndex": 6,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst/frame_06.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurst"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst/frame_07.svg",
    "frame": 7,
    "frameIndex": 7,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst/frame_07.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurst"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst/frame_08.svg",
    "frame": 8,
    "frameIndex": 8,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst/frame_08.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurst"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst/frame_09.svg",
    "frame": 9,
    "frameIndex": 9,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst/frame_09.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurst"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst/frame_10.svg",
    "frame": 10,
    "frameIndex": 10,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst/frame_10.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurst"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst/frame_11.svg",
    "frame": 11,
    "frameIndex": 11,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst/frame_11.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurst"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst/frame_12.svg",
    "frame": 12,
    "frameIndex": 12,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst/frame_12.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurst"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst/frame_13.svg",
    "frame": 13,
    "frameIndex": 13,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst/frame_13.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurst"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst/frame_14.svg",
    "frame": 14,
    "frameIndex": 14,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst/frame_14.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurst"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst/frame_15.svg",
    "frame": 15,
    "frameIndex": 15,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst/frame_15.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurst"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst_star/frame_00.svg",
    "frame": 0,
    "frameIndex": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst_star/frame_00.svg",
    "slug": "speed_burst_star",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurstStar"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_piece/frame_00.svg",
    "frame": 0,
    "frameIndex": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_piece/frame_00.svg",
    "slug": "mine_piece",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 472"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_piece/frame_01.svg",
    "frame": 1,
    "frameIndex": 1,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_piece/frame_01.svg",
    "slug": "mine_piece",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 472"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_piece/frame_02.svg",
    "frame": 2,
    "frameIndex": 2,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_piece/frame_02.svg",
    "slug": "mine_piece",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 472"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_piece/frame_03.svg",
    "frame": 3,
    "frameIndex": 3,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_piece/frame_03.svg",
    "slug": "mine_piece",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 472"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_piece/frame_04.svg",
    "frame": 4,
    "frameIndex": 4,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_piece/frame_04.svg",
    "slug": "mine_piece",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 472"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_piece/frame_05.svg",
    "frame": 5,
    "frameIndex": 5,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_piece/frame_05.svg",
    "slug": "mine_piece",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 472"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_explosion/frame_00.svg",
    "frame": 0,
    "frameIndex": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_explosion/frame_00.svg",
    "slug": "mine_explosion",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 976"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_explosion/frame_01.svg",
    "frame": 1,
    "frameIndex": 1,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_explosion/frame_01.svg",
    "slug": "mine_explosion",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 976"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_explosion/frame_02.svg",
    "frame": 2,
    "frameIndex": 2,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_explosion/frame_02.svg",
    "slug": "mine_explosion",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 976"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_explosion/frame_03.svg",
    "frame": 3,
    "frameIndex": 3,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_explosion/frame_03.svg",
    "slug": "mine_explosion",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 976"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_explosion/frame_04.svg",
    "frame": 4,
    "frameIndex": 4,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_explosion/frame_04.svg",
    "slug": "mine_explosion",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 976"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_explosion/frame_05.svg",
    "frame": 5,
    "frameIndex": 5,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_explosion/frame_05.svg",
    "slug": "mine_explosion",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 976"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_explosion/frame_06.svg",
    "frame": 6,
    "frameIndex": 6,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_explosion/frame_06.svg",
    "slug": "mine_explosion",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 976"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_explosion/frame_07.svg",
    "frame": 7,
    "frameIndex": 7,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_explosion/frame_07.svg",
    "slug": "mine_explosion",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 976"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_explosion/frame_08.svg",
    "frame": 8,
    "frameIndex": 8,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_explosion/frame_08.svg",
    "slug": "mine_explosion",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 976"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_explosion/frame_09.svg",
    "frame": 9,
    "frameIndex": 9,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_explosion/frame_09.svg",
    "slug": "mine_explosion",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 976"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_explosion/frame_10.svg",
    "frame": 10,
    "frameIndex": 10,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_explosion/frame_10.svg",
    "slug": "mine_explosion",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 976"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_explosion/frame_11.svg",
    "frame": 11,
    "frameIndex": 11,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_explosion/frame_11.svg",
    "slug": "mine_explosion",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 976"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_explosion/frame_12.svg",
    "frame": 12,
    "frameIndex": 12,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_explosion/frame_12.svg",
    "slug": "mine_explosion",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 976"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_explosion/frame_13.svg",
    "frame": 13,
    "frameIndex": 13,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_explosion/frame_13.svg",
    "slug": "mine_explosion",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 976"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_00.svg",
    "frame": 0,
    "frameIndex": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_00.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_01.svg",
    "frame": 1,
    "frameIndex": 1,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_01.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_02.svg",
    "frame": 2,
    "frameIndex": 2,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_02.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_03.svg",
    "frame": 3,
    "frameIndex": 3,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_03.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_04.svg",
    "frame": 4,
    "frameIndex": 4,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_04.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_05.svg",
    "frame": 5,
    "frameIndex": 5,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_05.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_06.svg",
    "frame": 6,
    "frameIndex": 6,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_06.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_07.svg",
    "frame": 7,
    "frameIndex": 7,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_07.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_08.svg",
    "frame": 8,
    "frameIndex": 8,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_08.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_09.svg",
    "frame": 9,
    "frameIndex": 9,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_09.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_10.svg",
    "frame": 10,
    "frameIndex": 10,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_10.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_11.svg",
    "frame": 11,
    "frameIndex": 11,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_11.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_12.svg",
    "frame": 12,
    "frameIndex": 12,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_12.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_13.svg",
    "frame": 13,
    "frameIndex": 13,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_13.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_14.svg",
    "frame": 14,
    "frameIndex": 14,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_14.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_15.svg",
    "frame": 15,
    "frameIndex": 15,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_15.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_16.svg",
    "frame": 16,
    "frameIndex": 16,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_16.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_17.svg",
    "frame": 17,
    "frameIndex": 17,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_17.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_18.svg",
    "frame": 18,
    "frameIndex": 18,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_18.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_19.svg",
    "frame": 19,
    "frameIndex": 19,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_19.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_20.svg",
    "frame": 20,
    "frameIndex": 20,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_20.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_21.svg",
    "frame": 21,
    "frameIndex": 21,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_21.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_22.svg",
    "frame": 22,
    "frameIndex": 22,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_22.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_23.svg",
    "frame": 23,
    "frameIndex": 23,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_23.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_24.svg",
    "frame": 24,
    "frameIndex": 24,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_24.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_25.svg",
    "frame": 25,
    "frameIndex": 25,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_25.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_26.svg",
    "frame": 26,
    "frameIndex": 26,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_26.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_27.svg",
    "frame": 27,
    "frameIndex": 27,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_27.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_28.svg",
    "frame": 28,
    "frameIndex": 28,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_28.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_29.svg",
    "frame": 29,
    "frameIndex": 29,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_29.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_30.svg",
    "frame": 30,
    "frameIndex": 30,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_30.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_31.svg",
    "frame": 31,
    "frameIndex": 31,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_31.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear/frame_32.svg",
    "frame": 32,
    "frameIndex": 32,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear/frame_32.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "items",
    "exportPath": "items/display/none.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/none.svg",
    "slug": "none",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/jet_pack.svg",
    "frame": 5,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/jet_pack.svg",
    "slug": "jet_pack",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/mine.svg",
    "frame": 10,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/mine.svg",
    "slug": "mine",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/speed_burst.svg",
    "frame": 15,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/speed_burst.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/super_jump.svg",
    "frame": 20,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/super_jump.svg",
    "slug": "super_jump",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/teleport.svg",
    "frame": 25,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/teleport.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/lightning.svg",
    "frame": 30,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/lightning.svg",
    "slug": "lightning",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/laser.svg",
    "frame": 35,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/laser.svg",
    "slug": "laser",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/sword.svg",
    "frame": 40,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/sword.svg",
    "slug": "sword",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/ice_wave.svg",
    "frame": 45,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/ice_wave.svg",
    "slug": "ice_wave",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  }
];

function log(message) {
	fl.trace("[PR2 SVG Export] " + message);
}

function dirname(uri) {
	return uri.replace(/\/[^\/]*$/, "");
}

function mkdirs(uri) {
	var parts = uri.split("/");
	if (parts.length < 4) {
		return;
	}
	var current = parts[0] + "//" + parts[2];
	for (var i = 3; i < parts.length; i++) {
		current += "/" + parts[i];
		if (!FLfile.exists(current)) {
			FLfile.createFolder(current);
		}
	}
}

function selectFrame(timeline, frameIndex) {
	try {
		timeline.currentFrame = frameIndex;
	} catch (e) {
	}
	try {
		timeline.setSelectedFrames(frameIndex, frameIndex + 1, true);
	} catch (e) {
	}
}

function stageSymbol(doc, symbolName, frame) {
	doc.library.addItemToDocument({ x: 0, y: 0 }, symbolName);
	var instance = doc.selection && doc.selection.length > 0 ? doc.selection[0] : null;
	if (!instance) {
		throw new Error("Could not stage library item: " + symbolName);
	}
	try {
		instance.symbolType = "graphic";
	} catch (e) {
	}
	try {
		instance.firstFrame = frame;
	} catch (e) {
	}
	try {
		instance.loop = "single frame";
	} catch (e) {
	}
}

function exportCurrentView(outputUri) {
	mkdirs(dirname(outputUri));
	fl.runScript(ADOBE_SVG_EXPORTER_URI, "exportSVG", "", outputUri, true, "", false, false, 0, 0);
}

function exportJob(doc, job) {
	log("[" + job.category + "] " + job.exportPath + " from " + job.symbolName + " frame " + job.frame);
	try {
		doc.selectAll();
		doc.deleteSelection();
	} catch (e) {
	}
	stageSymbol(doc, job.symbolName, job.frame);
	exportCurrentView(job.outputUri);
	try {
		doc.selectAll();
		doc.deleteSelection();
	} catch (e) {
	}
}

function run() {
	log("opening " + SOURCE_FLA_URI);
	var doc = fl.openDocument(SOURCE_FLA_URI);
	if (!doc) {
		throw new Error("Could not open source FLA: " + SOURCE_FLA_URI);
	}
	for (var i = 0; i < JOBS.length; i++) {
		exportJob(doc, JOBS[i]);
	}
	log("complete: " + JOBS.length + " SVG exports");
}

run();
