// Generated by tools/generate_other_assets_jsfl.py. Do not edit by hand.
// Open this file with Adobe Animate to export non-character SVG assets.
// Output lands directly in vector-art/svg/.
// macOS direct run:
// "/Applications/Adobe Animate 2024/Adobe Animate 2024.app/Contents/MacOS/Adobe Animate 2024" vector-art/export-other-assets-svg.jsfl

var SOURCE_FLA_URI = "file:///Users/jacobgrahn/Documents/platform-racing-2-client/flash/platform-racing-2.fla";
var ADOBE_SVG_EXPORTER_URI = "file:///Applications/Adobe%20Animate%202024/Adobe%20Animate%202024.app/Contents/Common/Configuration/Extensions/ExportSVG/jsfl/Export%20SVG.jsfl";
var JOBS = [
  {
    "category": "backgrounds",
    "exportPath": "backgrounds/bg1.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/backgrounds/bg1.svg",
    "slug": "bg1",
    "symbolName": "UI/Pages/Levels/Backgrounds/bg1"
  },
  {
    "category": "backgrounds",
    "exportPath": "backgrounds/bg2.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/backgrounds/bg2.svg",
    "slug": "bg2",
    "symbolName": "UI/Pages/Levels/Backgrounds/bg2"
  },
  {
    "category": "backgrounds",
    "exportPath": "backgrounds/bg3.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/backgrounds/bg3.svg",
    "slug": "bg3",
    "symbolName": "UI/Pages/Levels/Backgrounds/bg3"
  },
  {
    "category": "backgrounds",
    "exportPath": "backgrounds/bg4.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/backgrounds/bg4.svg",
    "slug": "bg4",
    "symbolName": "UI/Pages/Levels/Backgrounds/bg4"
  },
  {
    "category": "backgrounds",
    "exportPath": "backgrounds/bg5.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/backgrounds/bg5.svg",
    "slug": "bg5",
    "symbolName": "UI/Pages/Levels/Backgrounds/bg5"
  },
  {
    "category": "backgrounds",
    "exportPath": "backgrounds/bg6.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/backgrounds/bg6.svg",
    "slug": "bg6",
    "symbolName": "UI/Pages/Levels/Backgrounds/bg6"
  },
  {
    "category": "backgrounds",
    "exportPath": "backgrounds/bg7.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/backgrounds/bg7.svg",
    "slug": "bg7",
    "symbolName": "UI/Pages/Levels/Backgrounds/bg7"
  },
  {
    "category": "stamps",
    "exportPath": "stamps/petrified_tree.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/stamps/petrified_tree.svg",
    "slug": "petrified_tree",
    "symbolName": "UI/Pages/Levels/Stamps/PetrifiedTree"
  },
  {
    "category": "stamps",
    "exportPath": "stamps/rock1.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/stamps/rock1.svg",
    "slug": "rock1",
    "symbolName": "UI/Pages/Levels/Stamps/rock1"
  },
  {
    "category": "stamps",
    "exportPath": "stamps/rock2.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/stamps/rock2.svg",
    "slug": "rock2",
    "symbolName": "UI/Pages/Levels/Stamps/rock2"
  },
  {
    "category": "stamps",
    "exportPath": "stamps/spire1.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/stamps/spire1.svg",
    "slug": "spire1",
    "symbolName": "UI/Pages/Levels/Stamps/spire1"
  },
  {
    "category": "stamps",
    "exportPath": "stamps/spire2.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/stamps/spire2.svg",
    "slug": "spire2",
    "symbolName": "UI/Pages/Levels/Stamps/spire2"
  },
  {
    "category": "stamps",
    "exportPath": "stamps/tree1.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/stamps/tree1.svg",
    "slug": "tree1",
    "symbolName": "UI/Pages/Levels/Stamps/tree1"
  },
  {
    "category": "stamps",
    "exportPath": "stamps/tree2.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/stamps/tree2.svg",
    "slug": "tree2",
    "symbolName": "UI/Pages/Levels/Stamps/tree2"
  },
  {
    "category": "stamps",
    "exportPath": "stamps/tree3.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/stamps/tree3.svg",
    "slug": "tree3",
    "symbolName": "UI/Pages/Levels/Stamps/tree3"
  },
  {
    "category": "effects",
    "exportPath": "effects/laser_shot.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/laser_shot.svg",
    "slug": "laser_shot",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LaserShot"
  },
  {
    "category": "effects",
    "exportPath": "effects/lightning_bolt.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/lightning_bolt.svg",
    "slug": "lightning_bolt",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/LightningBolt"
  },
  {
    "category": "effects",
    "exportPath": "effects/slash.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/slash.svg",
    "slug": "slash",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Slash"
  },
  {
    "category": "effects",
    "exportPath": "effects/sting.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/sting.svg",
    "slug": "sting",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Sting"
  },
  {
    "category": "effects",
    "exportPath": "effects/teleport.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/teleport.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Teleport"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurst"
  },
  {
    "category": "effects",
    "exportPath": "effects/speed_burst_star.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/speed_burst_star.svg",
    "slug": "speed_burst_star",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/SpeedBurst/SpeedBurstStar"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_piece.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_piece.svg",
    "slug": "mine_piece",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 472"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_explosion.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_explosion.svg",
    "slug": "mine_explosion",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 976"
  },
  {
    "category": "effects",
    "exportPath": "effects/mine_appear.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/effects/mine_appear.svg",
    "slug": "mine_appear",
    "symbolName": "UI/Pages/Levels/In-Game/Effects/Mine/Symbol 1020"
  },
  {
    "category": "items",
    "exportPath": "items/display/none.svg",
    "frame": 0,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/none.svg",
    "slug": "none",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/jet_pack.svg",
    "frame": 5,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/jet_pack.svg",
    "slug": "jet_pack",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/mine.svg",
    "frame": 10,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/mine.svg",
    "slug": "mine",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/speed_burst.svg",
    "frame": 15,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/speed_burst.svg",
    "slug": "speed_burst",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/super_jump.svg",
    "frame": 20,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/super_jump.svg",
    "slug": "super_jump",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/teleport.svg",
    "frame": 25,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/teleport.svg",
    "slug": "teleport",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/lightning.svg",
    "frame": 30,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/lightning.svg",
    "slug": "lightning",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/laser.svg",
    "frame": 35,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/laser.svg",
    "slug": "laser",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/sword.svg",
    "frame": 40,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/sword.svg",
    "slug": "sword",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "items",
    "exportPath": "items/display/ice_wave.svg",
    "frame": 45,
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/items/display/ice_wave.svg",
    "slug": "ice_wave",
    "symbolName": "UI/Pages/Levels/In-Game/ItemDisplay"
  },
  {
    "category": "intro",
    "exportPath": "intro/kongregate/symbol_27.svg",
    "frame": 0,
    "group": "kongregate",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/intro/kongregate/symbol_27.svg",
    "slug": "symbol_27",
    "symbolName": "MovieClips/Symbol 27"
  },
  {
    "category": "intro",
    "exportPath": "intro/kongregate/symbol_30.svg",
    "frame": 0,
    "group": "kongregate",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/intro/kongregate/symbol_30.svg",
    "slug": "symbol_30",
    "symbolName": "MovieClips/Symbol 30"
  },
  {
    "category": "intro",
    "exportPath": "intro/kongregate/symbol_32.svg",
    "frame": 0,
    "group": "kongregate",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/intro/kongregate/symbol_32.svg",
    "slug": "symbol_32",
    "symbolName": "MovieClips/Symbol 32"
  },
  {
    "category": "intro",
    "exportPath": "intro/kongregate/symbol_34.svg",
    "frame": 0,
    "group": "kongregate",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/intro/kongregate/symbol_34.svg",
    "slug": "symbol_34",
    "symbolName": "MovieClips/Symbol 34"
  },
  {
    "category": "intro",
    "exportPath": "intro/kongregate/symbol_36.svg",
    "frame": 0,
    "group": "kongregate",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/intro/kongregate/symbol_36.svg",
    "slug": "symbol_36",
    "symbolName": "MovieClips/Symbol 36"
  },
  {
    "category": "intro",
    "exportPath": "intro/kongregate/symbol_38.svg",
    "frame": 0,
    "group": "kongregate",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/intro/kongregate/symbol_38.svg",
    "slug": "symbol_38",
    "symbolName": "MovieClips/Symbol 38"
  },
  {
    "category": "intro",
    "exportPath": "intro/kongregate/symbol_40.svg",
    "frame": 0,
    "group": "kongregate",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/intro/kongregate/symbol_40.svg",
    "slug": "symbol_40",
    "symbolName": "MovieClips/Symbol 40"
  },
  {
    "category": "intro",
    "exportPath": "intro/kongregate/symbol_41.svg",
    "frame": 0,
    "group": "kongregate",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/intro/kongregate/symbol_41.svg",
    "slug": "symbol_41",
    "symbolName": "MovieClips/Symbol 41"
  },
  {
    "category": "intro",
    "exportPath": "intro/kongregate/symbol_44.svg",
    "frame": 0,
    "group": "kongregate",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/intro/kongregate/symbol_44.svg",
    "slug": "symbol_44",
    "symbolName": "MovieClips/Symbol 44"
  },
  {
    "category": "intro",
    "exportPath": "intro/kongregate/symbol_47.svg",
    "frame": 0,
    "group": "kongregate",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/intro/kongregate/symbol_47.svg",
    "slug": "symbol_47",
    "symbolName": "MovieClips/Symbol 47"
  },
  {
    "category": "intro",
    "exportPath": "intro/kongregate/symbol_49.svg",
    "frame": 0,
    "group": "kongregate",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/intro/kongregate/symbol_49.svg",
    "slug": "symbol_49",
    "symbolName": "MovieClips/Symbol 49"
  },
  {
    "category": "intro",
    "exportPath": "intro/kongregate/symbol_52.svg",
    "frame": 0,
    "group": "kongregate",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/intro/kongregate/symbol_52.svg",
    "slug": "symbol_52",
    "symbolName": "MovieClips/Symbol 52"
  },
  {
    "category": "intro",
    "exportPath": "intro/kongregate/graphic_28.svg",
    "frame": 0,
    "group": "kongregate",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/intro/kongregate/graphic_28.svg",
    "slug": "graphic_28",
    "symbolName": "Graphics/Symbol 28"
  },
  {
    "category": "intro",
    "exportPath": "intro/kongregate/graphic_42.svg",
    "frame": 0,
    "group": "kongregate",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/intro/kongregate/graphic_42.svg",
    "slug": "graphic_42",
    "symbolName": "Graphics/Symbol 42"
  },
  {
    "category": "intro",
    "exportPath": "intro/kongregate/graphic_43.svg",
    "frame": 0,
    "group": "kongregate",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/vector-art/svg/intro/kongregate/graphic_43.svg",
    "slug": "graphic_43",
    "symbolName": "Graphics/Symbol 43"
  }
];

function log(message) {
	fl.trace("[PR2 SVG Export] " + message);
}

function dirname(uri) {
	return uri.replace(/\/[^\/]*$/, "");
}

function mkdirs(uri) {
	var parts = uri.split("/");
	if (parts.length < 4) {
		return;
	}
	var current = parts[0] + "//" + parts[2];
	for (var i = 3; i < parts.length; i++) {
		current += "/" + parts[i];
		if (!FLfile.exists(current)) {
			FLfile.createFolder(current);
		}
	}
}

function selectFrame(timeline, frameIndex) {
	try {
		timeline.currentFrame = frameIndex;
	} catch (e) {
	}
	try {
		timeline.setSelectedFrames(frameIndex, frameIndex + 1, true);
	} catch (e) {
	}
}

function stageSymbol(doc, symbolName, frame) {
	doc.library.addItemToDocument({ x: 0, y: 0 }, symbolName);
	var instance = doc.selection && doc.selection.length > 0 ? doc.selection[0] : null;
	if (!instance) {
		throw new Error("Could not stage library item: " + symbolName);
	}
	// `addItemToDocument({x:0,y:0})` places many library items by their visual
	// center. Resetting the instance matrix preserves the symbol registration
	// point, which is what timeline matrices in the XFL reference.
	try {
		instance.matrix = { a: 1, b: 0, c: 0, d: 1, tx: 0, ty: 0 };
	} catch (e) {
	}
	try {
		instance.symbolType = "graphic";
	} catch (e) {
	}
	try {
		instance.firstFrame = frame;
	} catch (e) {
	}
	try {
		instance.loop = "single frame";
	} catch (e) {
	}
}

function exportCurrentView(outputUri) {
	mkdirs(dirname(outputUri));
	fl.runScript(ADOBE_SVG_EXPORTER_URI, "exportSVG", "", outputUri, true, "", false, false, 0, 0);
}

function exportJob(doc, job) {
	log("[" + job.category + "] " + job.exportPath + " from " + job.symbolName + " frame " + job.frame);
	try {
		doc.selectAll();
		doc.deleteSelection();
	} catch (e) {
	}
	stageSymbol(doc, job.symbolName, job.frame);
	exportCurrentView(job.outputUri);
	try {
		doc.selectAll();
		doc.deleteSelection();
	} catch (e) {
	}
}

function run() {
	log("opening " + SOURCE_FLA_URI);
	var doc = fl.openDocument(SOURCE_FLA_URI);
	if (!doc) {
		throw new Error("Could not open source FLA: " + SOURCE_FLA_URI);
	}
	for (var i = 0; i < JOBS.length; i++) {
		exportJob(doc, JOBS[i]);
	}
	log("complete: " + JOBS.length + " SVG exports");
}

run();
