// Generated by tools/generate_block_bitmap_jsfl.py. Do not edit by hand.
// Open this file with Adobe Animate to export block bitmap tiles.
// Output goes directly to assets/blocks/.
// macOS direct run:
// "/Applications/Adobe Animate 2024/Adobe Animate 2024.app/Contents/MacOS/Adobe Animate 2024" art/export-block-bitmaps.jsfl

var SOURCE_FLA_URI = "file:///Users/jacobgrahn/Documents/platform-racing-2-client/flash/platform-racing-2.fla";
var JOBS = [
  {
    "libraryName": "Images/bitmap9.png",
    "linkageClassName": "Basic1Bitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/basic1.png",
    "slug": "basic1"
  },
  {
    "libraryName": "Images/bitmap15.png",
    "linkageClassName": "Basic2Bitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/basic2.png",
    "slug": "basic2"
  },
  {
    "libraryName": "Images/bitmap21.png",
    "linkageClassName": "Basic3Bitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/basic3.png",
    "slug": "basic3"
  },
  {
    "libraryName": "Images/bitmap13.png",
    "linkageClassName": "Basic4Bitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/basic4.png",
    "slug": "basic4"
  },
  {
    "libraryName": "Images/bitmap25.png",
    "linkageClassName": "BrickBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/brick.png",
    "slug": "brick"
  },
  {
    "libraryName": "Images/bitmap20.jpg",
    "linkageClassName": "CrumbleBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/crumble.png",
    "slug": "crumble"
  },
  {
    "libraryName": "Images/customstats.png",
    "linkageClassName": "CustomStatsBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/custom_stats.png",
    "slug": "custom_stats"
  },
  {
    "libraryName": "Images/bitmap5.png",
    "linkageClassName": "FinishBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/finish.png",
    "slug": "finish"
  },
  {
    "libraryName": "Images/bitmap18.png",
    "linkageClassName": "HappyBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/happy.png",
    "slug": "happy"
  },
  {
    "libraryName": "Images/bitmap24.png",
    "linkageClassName": "HeartBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/heart.png",
    "slug": "heart"
  },
  {
    "libraryName": "Images/bitmap17.jpg",
    "linkageClassName": "IceBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/ice.png",
    "slug": "ice"
  },
  {
    "libraryName": "Images/bitmap10.jpg",
    "linkageClassName": "InfiniteItemBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/infinite_item.png",
    "slug": "infinite_item"
  },
  {
    "libraryName": "Images/bitmap7.png",
    "linkageClassName": "ItemBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/item.png",
    "slug": "item"
  },
  {
    "libraryName": "Images/bitmap71.jpg",
    "linkageClassName": "JiggminLogo",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/jiggmin_logo.png",
    "slug": "jiggmin_logo"
  },
  {
    "libraryName": "Images/bitmap19.jpg",
    "linkageClassName": "MineBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/mine_block.png",
    "slug": "mine_block"
  },
  {
    "libraryName": "Images/bitmap6.png",
    "linkageClassName": "MoveBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/move.png",
    "slug": "move"
  },
  {
    "libraryName": "Images/bitmap3.png",
    "linkageClassName": "PushBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/push.png",
    "slug": "push"
  },
  {
    "libraryName": "Images/bitmap8.png",
    "linkageClassName": "RotateLeftBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/rotate_left.png",
    "slug": "rotate_left"
  },
  {
    "libraryName": "Images/bitmap16.png",
    "linkageClassName": "RotateRightBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/rotate_right.png",
    "slug": "rotate_right"
  },
  {
    "libraryName": "Images/bitmap23.png",
    "linkageClassName": "SadBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/sad.png",
    "slug": "sad"
  },
  {
    "libraryName": "Images/bitmap14.png",
    "linkageClassName": "SafetyNetBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/safety_net.png",
    "slug": "safety_net"
  },
  {
    "libraryName": "Images/bitmap12.png",
    "linkageClassName": "StartBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/start.png",
    "slug": "start"
  },
  {
    "libraryName": "Images/teleblock_borderfix_resize.png",
    "linkageClassName": "TeleportBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/teleport_block.png",
    "slug": "teleport_block"
  },
  {
    "libraryName": "Images/bitmap11.png",
    "linkageClassName": "TimeBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/time.png",
    "slug": "time"
  },
  {
    "libraryName": "Images/bitmap22.png",
    "linkageClassName": "VanishBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/vanish.png",
    "slug": "vanish"
  },
  {
    "libraryName": "Images/bitmap4.png",
    "linkageClassName": "WaterBitmap",
    "outputUri": "file:///Users/jacobgrahn/Documents/platform-racing-2-client/assets/blocks/water.png",
    "slug": "water"
  }
];

function log(message) {
	fl.trace("[PR2 Bitmap Export] " + message);
}

function dirname(uri) {
	return uri.replace(/\/[^\/]*$/, "");
}

function mkdirs(uri) {
	var parts = uri.split("/");
	if (parts.length < 4) {
		return;
	}
	var current = parts[0] + "//" + parts[2];
	for (var i = 3; i < parts.length; i++) {
		current += "/" + parts[i];
		if (!FLfile.exists(current)) {
			FLfile.createFolder(current);
		}
	}
}

function findLibraryItem(doc, libraryName) {
	var items = doc.library.items;
	for (var i = 0; i < items.length; i++) {
		if (items[i].name === libraryName) {
			return items[i];
		}
	}
	return null;
}

function exportBitmapJob(doc, job) {
	log(job.slug + " (" + job.libraryName + ") -> " + job.outputUri);
	var item = findLibraryItem(doc, job.libraryName);
	if (!item) {
		log("WARNING: library item not found: " + job.libraryName);
		return;
	}
	if (item.itemType !== "bitmap") {
		log("WARNING: item is not a bitmap: " + job.libraryName + " (type=" + item.itemType + ")");
		return;
	}
	mkdirs(dirname(job.outputUri));
	item.exportToFile(job.outputUri);
}

function run() {
	log("opening " + SOURCE_FLA_URI);
	var doc = fl.openDocument(SOURCE_FLA_URI);
	if (!doc) {
		throw new Error("Could not open source FLA: " + SOURCE_FLA_URI);
	}
	for (var i = 0; i < JOBS.length; i++) {
		exportBitmapJob(doc, JOBS[i]);
	}
	log("complete: " + JOBS.length + " bitmap exports");
}

run();
