// Generated by tools/generate_native_assets.py. Do not edit.

package pr2.assets;

final class NativeAssetIds {
	private function new() {}
}

enum abstract StaticSvg(String) to String {
	var ArrowOverlay = "assets/svg/blocks/arrow_overlay.svg";
	var Arrow2Overlay = "assets/svg/blocks/arrow2_overlay.svg";
	var ArrowButtonDisabled = "assets/svg/timeline/graphics_symbol_1182_fe505e771a/t00_l000_f0000_r00.svg";
	var ArrowButtonDown = "assets/svg/timeline/graphics_symbol_1181_8da2d701eb/t00_l000_f0000_r00.svg";
	var ArrowButtonOver = "assets/svg/timeline/graphics_symbol_1180_178f938050/t00_l000_f0000_r00.svg";
	var ArrowButtonUp = "assets/svg/timeline/graphics_symbol_1179_688a9ff27c/t00_l000_f0000_r00.svg";
	var EggOverlay = "assets/svg/blocks/egg_overlay.svg";
	var DjinnIce = "assets/svg/timeline/graphics_symbol_26_97e4207de0/t00_l000_f0000_r00.svg";
	var HeartHighlight = "assets/svg/timeline/graphics_symbol_917_14a7be666e/t00_l001_f0000_r00.svg";
	var HeartMain = "assets/svg/timeline/graphics_symbol_917_14a7be666e/t00_l002_f0000_r00.svg";
	var HeartShadow = "assets/svg/timeline/graphics_symbol_917_14a7be666e/t00_l000_f0000_r00.svg";
	var LoginBackgroundFar = "assets/svg/login/bg_far.svg";
	var LoginBackgroundMid = "assets/svg/login/bg_mid.svg";
	var LoginBackgroundSky = "assets/svg/login/bg_sky.svg";
	var QuantityPanel = "assets/svg/timeline/ui_shadowbg_95643069a8/t00_l000_f0000_r00.svg";
	var RatingStarHighlight = "assets/svg/timeline/movieclips_symbol_1064_2f2dcafe56/t00_l001_f0005_r00.svg";
	var RockStamp = "assets/svg/stamps/rock1.svg";
	var LobbyTabOver = "assets/svg/timeline/movieclips_pr2_graphics_1_apr_2014_fla_symbol_1224_f93a5fd6a6/t00_l002_f0005_r00.svg";
	var LobbyTabSelectedOverlay = "assets/svg/timeline/graphics_symbol_1223_06a8b36222/t00_l000_f0000_r00.svg";
	var LobbyTabUp = "assets/svg/timeline/movieclips_pr2_graphics_1_apr_2014_fla_symbol_1224_f93a5fd6a6/t00_l002_f0000_r00.svg";
	var SpeedBurstStar = "assets/svg/timeline/ui_pages_levels_in_game_effects_speedburst_speedburststar_64db9149b6/t00_l000_f0000_r00.svg";
	var ScrollArrowDown = "assets/svg/timeline/components_component_assets_scrollbarskins_scrollarrowdown_upski_5a4fa47e32/t00_l001_f0000_r00.svg";
	var ScrollArrowUp = "assets/svg/timeline/components_component_assets_scrollbarskins_scrollarrowup_upskin_03aeb6088e/t00_l001_f0000_r00.svg";
	var ScrollThumb = "assets/svg/timeline/components_component_assets_scrollbarskins_scrollthumb_upskin_114bd98aac/t00_l000_f0000_r00.svg";
	var ScrollThumbIcon = "assets/svg/timeline/components_component_assets_scrollbarskins_scrollbar_thumbicon_9dca80a08b/t00_l000_f0000_r00.svg";
	var ScrollTrack = "assets/svg/timeline/components_component_assets_scrollbarskins_scrolltrack_skin_1c49414a50/t00_l000_f0000_r00.svg";
	var TimerPanel = "assets/svg/timeline/ui_popups_outside_levels_bg_d14a954e12/t00_l000_f0000_r00.svg";
	var TreeStamp = "assets/svg/stamps/tree1.svg";
}

enum abstract BitmapAsset(String) to String {
	var BasicBlock = "assets/blocks/basic1.png";
	var FrontLoginBackground = "assets/login/bg_front@2x.png";
	var Mine = "assets/bitmaps/mine.jpg";
	var TeleportBlock = "assets/blocks/teleport_block.png";
}

enum abstract FontAsset(String) to String {
	var Body = "Arial";
	var Display = "Gwibble";
	var Icons = "FontAwesome";
	var Interface = "Verdana";
}

enum abstract SoundAsset(String) to String {
	var ButtonClick = "assets/audio/sfx/menu_noodle_town_2.mp3";
	var CountdownGo = "assets/audio/sfx/countdown_go.mp3";
	var CountdownReady = "assets/audio/sfx/countdown_ready.mp3";
	var Jump = "assets/audio/sfx/jump.mp3";
}
