// Generated by tools/generate_native_assets.py. Do not edit.

package pr2.assets;

final class NativeAssetIds {
	private function new() {}
}

enum abstract StaticSvg(String) to String {
	var ArrowOverlay = "assets/svg/blocks/arrow_overlay.svg";
	var EggOverlay = "assets/svg/blocks/egg_overlay.svg";
	var LoginBackgroundFar = "assets/svg/login/bg_far.svg";
	var LoginBackgroundMid = "assets/svg/login/bg_mid.svg";
	var LoginBackgroundSky = "assets/svg/login/bg_sky.svg";
	var RockStamp = "assets/svg/stamps/rock1.svg";
	var TreeStamp = "assets/svg/stamps/tree1.svg";
}

enum abstract BitmapAsset(String) to String {
	var BasicBlock = "assets/blocks/basic1.png";
	var FrontLoginBackground = "assets/login/bg_front@2x.png";
	var TeleportBlock = "assets/blocks/teleport_block.png";
}

enum abstract FontAsset(String) to String {
	var Body = "Arial";
	var Display = "Gwibble";
	var Icons = "FontAwesome";
}

enum abstract SoundAsset(String) to String {
	var ButtonClick = "assets/audio/sfx/menu_noodle_town_2.mp3";
	var CountdownGo = "assets/audio/sfx/countdown_go.mp3";
	var CountdownReady = "assets/audio/sfx/countdown_ready.mp3";
	var Jump = "assets/audio/sfx/jump.mp3";
}
