// Generated by tools/generate_native_assets.py. Do not edit.

package pr2.assets;

final class NativeAssetIds {
	private function new() {}
}

enum abstract StaticSvg(String) to String {
	var ArrowOverlay = "assets/svg/blocks/arrow_overlay.svg";
	var EggOverlay = "assets/svg/blocks/egg_overlay.svg";
	var HeartHighlight = "assets/svg/timeline/graphics_symbol_917_14a7be666e/t00_l001_f0000_r00.svg";
	var HeartMain = "assets/svg/timeline/graphics_symbol_917_14a7be666e/t00_l002_f0000_r00.svg";
	var HeartShadow = "assets/svg/timeline/graphics_symbol_917_14a7be666e/t00_l000_f0000_r00.svg";
	var LoginBackgroundFar = "assets/svg/login/bg_far.svg";
	var LoginBackgroundMid = "assets/svg/login/bg_mid.svg";
	var LoginBackgroundSky = "assets/svg/login/bg_sky.svg";
	var QuantityPanel = "assets/svg/timeline/ui_shadowbg_95643069a8/t00_l000_f0000_r00.svg";
	var RockStamp = "assets/svg/stamps/rock1.svg";
	var TimerPanel = "assets/svg/timeline/ui_popups_outside_levels_bg_d14a954e12/t00_l000_f0000_r00.svg";
	var TreeStamp = "assets/svg/stamps/tree1.svg";
}

enum abstract BitmapAsset(String) to String {
	var BasicBlock = "assets/blocks/basic1.png";
	var FrontLoginBackground = "assets/login/bg_front@2x.png";
	var Mine = "assets/bitmaps/mine.jpg";
	var TeleportBlock = "assets/blocks/teleport_block.png";
}

enum abstract FontAsset(String) to String {
	var Body = "Arial";
	var Display = "Gwibble";
	var Icons = "FontAwesome";
	var Interface = "Verdana";
}

enum abstract SoundAsset(String) to String {
	var ButtonClick = "assets/audio/sfx/menu_noodle_town_2.mp3";
	var CountdownGo = "assets/audio/sfx/countdown_go.mp3";
	var CountdownReady = "assets/audio/sfx/countdown_ready.mp3";
	var Jump = "assets/audio/sfx/jump.mp3";
}
