#!/usr/bin/env python3
"""Generate the typed native-presentation asset identifiers."""

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "tools/native-assets.json"
OUTPUT = ROOT / "haxe/src/pr2/assets/NativeAssetIds.hx"


def source_path(asset_path: str) -> Path:
    if asset_path.startswith("assets/svg/"):
        return ROOT / "art/svg" / asset_path.removeprefix("assets/svg/")
    return ROOT / asset_path


def render_kind(type_name: str, entries: dict[str, str]) -> str:
    lines = [f"enum abstract {type_name}(String) to String {{"]
    for name, value in entries.items():
        lines.append(f'\tvar {name} = "{value}";')
    lines.append("}")
    return "\n".join(lines)


def render(data: dict[str, dict[str, str]]) -> str:
    sections = [
        "// Generated by tools/generate_native_assets.py. Do not edit.",
        "package pr2.assets;",
        "final class NativeAssetIds {\n\tprivate function new() {}\n}",
        render_kind("StaticSvg", data["svg"]),
        render_kind("BitmapAsset", data["bitmap"]),
        render_kind("FontAsset", data["font"]),
        render_kind("SoundAsset", data["sound"]),
    ]
    return "\n\n".join(sections) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = json.loads(MANIFEST.read_text())
    missing = [value for kind in ("svg", "bitmap", "sound") for value in data[kind].values() if not source_path(value).is_file()]
    if missing:
        raise SystemExit("Missing native assets: " + ", ".join(missing))
    expected = render(data)
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text() != expected:
            raise SystemExit("Native asset identifiers are stale; run tools/generate_native_assets.py")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
