#!/usr/bin/env python3
"""
Generate a JSFL batch script to export PR2 block bitmap tiles from the Flash library.

Block bitmaps are raster images embedded in the XFL (not vector art).  Adobe
Animate's BitmapItem.exportToFile() API exports each one to a PNG.  The output
goes directly to assets/blocks/ -- no SVG or rasterization step needed.

Run: python3 tools/generate_block_bitmap_jsfl.py
Then open art/export-block-bitmaps.jsfl in Adobe Animate.

Run with Adobe Animate on macOS:
  "/Applications/Adobe Animate 2024/Adobe Animate 2024.app/Contents/MacOS/Adobe Animate 2024" art/export-block-bitmaps.jsfl
"""

import argparse
import json
import os
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


DEFAULT_XFL_DOM = os.path.join("flash", "platform-racing-2-xfl", "DOMDocument.xml")
DEFAULT_FLA = os.path.join("flash", "platform-racing-2.fla")
DEFAULT_PNG_ROOT = os.path.join("assets", "blocks")
DEFAULT_OUT = os.path.join("art", "export-block-bitmaps.jsfl")

NS = "{http://ns.adobe.com/xfl/2008/}"

# Human-readable slug for each linkage class (game-meaningful name first).
SLUG_OVERRIDES = {
    "Basic1Bitmap":       "basic1",
    "Basic2Bitmap":       "basic2",
    "Basic3Bitmap":       "basic3",
    "Basic4Bitmap":       "basic4",
    "BrickBitmap":        "brick",
    "CrumbleBitmap":      "crumble",
    "CustomStatsBitmap":  "custom_stats",
    "FinishBitmap":       "finish",
    "HappyBitmap":        "happy",
    "HeartBitmap":        "heart",
    "IceBitmap":          "ice",
    "InfiniteItemBitmap": "infinite_item",
    "ItemBitmap":         "item",
    "JiggminLogo":        "jiggmin_logo",
    "MineBitmap":         "mine_block",
    "MoveBitmap":         "move",
    "PushBitmap":         "push",
    "RotateLeftBitmap":   "rotate_left",
    "RotateRightBitmap":  "rotate_right",
    "SadBitmap":          "sad",
    "SafetyNetBitmap":    "safety_net",
    "StartBitmap":        "start",
    "TeleportBitmap":     "teleport_block",
    "TimeBitmap":         "time",
    "VanishBitmap":       "vanish",
    "WaterBitmap":        "water",
}


def camel_to_slug(name):
    name = re.sub(r"Bitmap$", "", name)
    name = re.sub(r"([A-Z])", r"_\1", name).lstrip("_")
    return name.lower()


def parse_bitmap_items(dom_path):
    tree = ET.parse(dom_path)
    root = tree.getroot()
    items = []
    for item in root.iter(f"{NS}DOMBitmapItem"):
        linkage = item.get("linkageClassName")
        if not linkage:
            continue
        library_name = item.get("name", "")
        slug = SLUG_OVERRIDES.get(linkage) or camel_to_slug(linkage)
        items.append({
            "libraryName": library_name,
            "linkageClassName": linkage,
            "slug": slug,
        })
    return sorted(items, key=lambda x: x["slug"])


def file_uri(path):
    return Path(path).resolve().as_uri()


def js_string(value):
    return json.dumps(value)


def build_jobs(bitmap_items, png_root):
    root = Path(png_root).resolve()
    jobs = []
    for item in bitmap_items:
        output_path = root / f"{item['slug']}.png"
        jobs.append({
            "libraryName":      item["libraryName"],
            "linkageClassName": item["linkageClassName"],
            "slug":             item["slug"],
            "outputUri":        output_path.as_uri(),
        })
    return jobs


def jsfl_source(jobs, fla_uri):
    return f"""// Generated by tools/generate_block_bitmap_jsfl.py. Do not edit by hand.
// Open this file with Adobe Animate to export block bitmap tiles.
// Output goes directly to assets/blocks/.
// macOS direct run:
// "/Applications/Adobe Animate 2024/Adobe Animate 2024.app/Contents/MacOS/Adobe Animate 2024" art/export-block-bitmaps.jsfl

var SOURCE_FLA_URI = {js_string(fla_uri)};
var JOBS = {json.dumps(jobs, indent=2, sort_keys=True)};

function log(message) {{
\tfl.trace("[PR2 Bitmap Export] " + message);
}}

function dirname(uri) {{
\treturn uri.replace(/\\/[^\\/]*$/, "");
}}

function mkdirs(uri) {{
\tvar parts = uri.split("/");
\tif (parts.length < 4) {{
\t\treturn;
\t}}
\tvar current = parts[0] + "//" + parts[2];
\tfor (var i = 3; i < parts.length; i++) {{
\t\tcurrent += "/" + parts[i];
\t\tif (!FLfile.exists(current)) {{
\t\t\tFLfile.createFolder(current);
\t\t}}
\t}}
}}

function findLibraryItem(doc, libraryName) {{
\tvar items = doc.library.items;
\tfor (var i = 0; i < items.length; i++) {{
\t\tif (items[i].name === libraryName) {{
\t\t\treturn items[i];
\t\t}}
\t}}
\treturn null;
}}

function exportBitmapJob(doc, job) {{
\tlog(job.slug + " (" + job.libraryName + ") -> " + job.outputUri);
\tvar item = findLibraryItem(doc, job.libraryName);
\tif (!item) {{
\t\tlog("WARNING: library item not found: " + job.libraryName);
\t\treturn;
\t}}
\tif (item.itemType !== "bitmap") {{
\t\tlog("WARNING: item is not a bitmap: " + job.libraryName + " (type=" + item.itemType + ")");
\t\treturn;
\t}}
\tmkdirs(dirname(job.outputUri));
\titem.exportToFile(job.outputUri);
}}

function run() {{
\tlog("opening " + SOURCE_FLA_URI);
\tvar doc = fl.openDocument(SOURCE_FLA_URI);
\tif (!doc) {{
\t\tthrow new Error("Could not open source FLA: " + SOURCE_FLA_URI);
\t}}
\tfor (var i = 0; i < JOBS.length; i++) {{
\t\texportBitmapJob(doc, JOBS[i]);
\t}}
\tlog("complete: " + JOBS.length + " bitmap exports");
}}

run();
"""


def parse_args(argv):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--xfl-dom", default=DEFAULT_XFL_DOM)
    parser.add_argument("--fla", default=DEFAULT_FLA)
    parser.add_argument("--png-root", default=DEFAULT_PNG_ROOT)
    parser.add_argument("--out", default=DEFAULT_OUT)
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv or sys.argv[1:])
    bitmap_items = parse_bitmap_items(args.xfl_dom)
    jobs = build_jobs(bitmap_items, args.png_root)
    source = jsfl_source(jobs, file_uri(args.fla))

    if args.out == "-":
        print(source, end="")
    else:
        os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
        with open(args.out, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(source)

    print(f"wrote {len(jobs)} bitmap export jobs to {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
