#!/usr/bin/env python3
"""
Generate deterministic Haxe source for the first PR2 asset graph catalog.

This is a one-time migration helper. It reads the Adobe-free XFL metadata
parser and writes native Haxe data structures under haxe/src so normal OpenFL
builds can consume committed source without parsing JSON or requiring Animate.
"""

import argparse
import os
import sys

from xfl_metadata import DEFAULT_XFL_DIR, build_metadata


DEFAULT_OUT_DIR = os.path.join("haxe", "src", "pr2", "generated", "assets")
GENERATED_NOTICE = "// Generated by tools/generate_haxe_assets.py. Do not edit by hand.\n"


def prune_display_element(element):
    pruned = {}
    for key, value in element.items():
        if key == "children":
            pruned[key] = [prune_display_element(child) for child in value]
        else:
            pruned[key] = value
    return pruned


def prune_frame(frame):
    pruned = dict(frame)
    if "elements" in pruned:
        pruned["elements"] = [prune_display_element(element) for element in pruned["elements"]]
    return pruned


def prune_layer(layer):
    pruned = dict(layer)
    pruned["frames"] = [prune_frame(frame) for frame in layer.get("frames", [])]
    return pruned


def prune_timeline(timeline):
    pruned = dict(timeline)
    pruned["layers"] = [prune_layer(layer) for layer in timeline.get("layers", [])]
    return pruned


def prune_symbol(symbol):
    pruned = dict(symbol)
    pruned["timelines"] = [prune_timeline(timeline) for timeline in symbol.get("timelines", [])]
    return pruned


def haxe_string(value):
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def haxe_number(value):
    if isinstance(value, float):
        return repr(value)
    return str(value)


def haxe_literal(value, indent=0):
    pad = "\t" * indent
    child_pad = "\t" * (indent + 1)

    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return haxe_number(value)
    if isinstance(value, str):
        return haxe_string(value)
    if isinstance(value, list):
        if not value:
            return "[]"
        items = [child_pad + haxe_literal(item, indent + 1) for item in value]
        return "[\n" + ",\n".join(items) + "\n" + pad + "]"
    if isinstance(value, dict):
        if not value:
            return "{}"
        items = []
        for key in sorted(value.keys()):
            items.append(child_pad + key + ": " + haxe_literal(value[key], indent + 1))
        return "{\n" + ",\n".join(items) + "\n" + pad + "}"
    raise TypeError(f"Unsupported value for Haxe literal: {value!r}")


def write_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)


def schema_source():
    return GENERATED_NOTICE + """package pr2.generated.assets;

typedef StageDef = {
\t@:optional var width:Int;
\t@:optional var height:Int;
}

typedef MatrixDef = {
\t@:optional var a:Float;
\t@:optional var b:Float;
\t@:optional var c:Float;
\t@:optional var d:Float;
\t@:optional var tx:Float;
\t@:optional var ty:Float;
}

typedef PointDef = {
\t@:optional var x:Float;
\t@:optional var y:Float;
}

typedef BoundsDef = {
\t@:optional var left:Float;
\t@:optional var top:Float;
\t@:optional var right:Float;
\t@:optional var bottom:Float;
}

typedef ColorTransformDef = {
\t@:optional var alphaMultiplier:Float;
\t@:optional var redMultiplier:Float;
\t@:optional var greenMultiplier:Float;
\t@:optional var blueMultiplier:Float;
\t@:optional var alphaOffset:Float;
\t@:optional var redOffset:Float;
\t@:optional var greenOffset:Float;
\t@:optional var blueOffset:Float;
}

typedef StyleValueDef = Dynamic;

typedef IndexedStyleDef = {
\t@:optional var index:Int;
\t@:optional var value:StyleValueDef;
}

typedef EdgeDef = {
\t@:optional var fillStyle0:Int;
\t@:optional var fillStyle1:Int;
\t@:optional var strokeStyle:Int;
\t@:optional var edges:String;
}

typedef FilterDef = {
\tvar type:String;
\t@:optional var blurX:Float;
\t@:optional var blurY:Float;
\t@:optional var strength:Float;
\t@:optional var quality:Int;
\t@:optional var color:Int;
\t@:optional var alpha:Float;
\t@:optional var angle:Float;
\t@:optional var distance:Float;
\t@:optional var inner:Bool;
\t@:optional var knockout:Bool;
\t@:optional var hideObject:Bool;
}

typedef DisplayElementDef = {
\tvar type:String;
\t@:optional var name:String;
\t@:optional var libraryItemName:String;
\t@:optional var symbolType:String;
\t@:optional var loop:String;
\t@:optional var firstFrame:Int;
\t@:optional var visible:Bool;
\t@:optional var blendMode:String;
\t@:optional var centerPoint3DX:Float;
\t@:optional var centerPoint3DY:Float;
\t@:optional var left:Float;
\t@:optional var width:Float;
\t@:optional var height:Float;
\t@:optional var matrix:MatrixDef;
\t@:optional var transformationPoint:PointDef;
\t@:optional var color:ColorTransformDef;
\t@:optional var fillStyleCount:Int;
\t@:optional var strokeStyleCount:Int;
\t@:optional var edgeCount:Int;
\t@:optional var fills:Array<IndexedStyleDef>;
\t@:optional var strokes:Array<IndexedStyleDef>;
\t@:optional var edges:Array<EdgeDef>;
\t@:optional var bounds:BoundsDef;
\t@:optional var filters:Array<FilterDef>;
\t@:optional var children:Array<DisplayElementDef>;
\t@:optional var x:Float;
\t@:optional var y:Float;
\t@:optional var objectWidth:Float;
\t@:optional var objectHeight:Float;
\t@:optional var topLeftRadius:Float;
\t@:optional var topRightRadius:Float;
\t@:optional var bottomLeftRadius:Float;
\t@:optional var bottomRightRadius:Float;
\t@:optional var startAngle:Float;
\t@:optional var endAngle:Float;
\t@:optional var innerRadius:Float;
\t@:optional var closePath:Bool;
\t@:optional var fill:StyleValueDef;
\t@:optional var stroke:StyleValueDef;
\t@:optional var text:String;
\t@:optional var textAttrs:Dynamic;
\t@:optional var componentParams:Dynamic;
}

typedef FrameDef = {
\t@:optional var index:Int;
\t@:optional var duration:Int;
\t@:optional var label:String;
\t@:optional var labelType:String;
\t@:optional var keyMode:Int;
\t@:optional var motionTweenScale:Bool;
\tvar elementCount:Int;
\tvar elementTypes:Array<String>;
\t@:optional var elements:Array<DisplayElementDef>;
}

typedef LayerDef = {
\tvar index:Int;
\t@:optional var name:String;
\t@:optional var color:String;
\t@:optional var visible:Bool;
\t@:optional var locked:Bool;
\t@:optional var layerType:String;
\tvar frameCount:Int;
\tvar frames:Array<FrameDef>;
}

typedef LabelDef = {
\tvar name:String;
\t@:optional var type:String;
\tvar frame:Int;
\tvar layer:Int;
}

typedef TimelineDef = {
\t@:optional var name:String;
\tvar layerCount:Int;
\tvar frameCount:Int;
\tvar labels:Array<LabelDef>;
\tvar layers:Array<LayerDef>;
}

typedef MediaAssetDef = {
\tvar type:String;
\t@:optional var name:String;
\t@:optional var href:String;
\t@:optional var itemID:String;
\t@:optional var linkageClassName:String;
\t@:optional var linkageIdentifier:String;
\t@:optional var bitmapDataHRef:String;
\t@:optional var soundDataHRef:String;
\t@:optional var frameRight:Int;
\t@:optional var frameBottom:Int;
\t@:optional var format:String;
\t@:optional var sampleCount:Int;
}

typedef SymbolAssetDef = {
\tvar href:String;
\tvar type:String;
\t@:optional var name:String;
\t@:optional var itemID:String;
\t@:optional var linkageClassName:String;
\t@:optional var linkageIdentifier:String;
\tvar timelines:Array<TimelineDef>;
}
"""


def constants_source(metadata):
    counts = metadata["counts"]
    document = metadata["document"]
    stage = metadata["stage"]
    return GENERATED_NOTICE + f"""package pr2.generated.assets;

final class AssetConstants {{
\tpublic static inline var XFL_DIR:String = {haxe_string(metadata["xflDir"])};
\tpublic static inline var STAGE_WIDTH:Int = {stage["width"]};
\tpublic static inline var STAGE_HEIGHT:Int = {stage["height"]};
\tpublic static inline var FRAME_RATE:Int = {document["frameRate"]};
\tpublic static inline var SYMBOL_COUNT:Int = {counts["symbolFiles"]};
\tpublic static inline var MEDIA_COUNT:Int = {counts["media"]};
\tpublic static inline var LINKAGE_CLASS_COUNT:Int = {counts["linkageClasses"]};
\tpublic static inline var TIMELINE_LAYER_COUNT:Int = {counts["timelineLayers"]};
\tpublic static inline var TIMELINE_FRAME_COUNT:Int = {counts["timelineFrames"]};
\tpublic static inline var TIMELINE_LABEL_COUNT:Int = {counts["timelineLabels"]};
\tpublic static inline var MAX_TIMELINE_FRAMES:Int = {counts["maxTimelineFrames"]};

\tprivate function new() {{}}
}}
"""


def catalog_source(metadata):
    media = metadata["media"]
    symbols = [prune_symbol(symbol) for symbol in metadata["symbols"]]
    linkage_classes = metadata["linkageClasses"]
    return GENERATED_NOTICE + """package pr2.generated.assets;

import pr2.generated.assets.AssetTypes.MediaAssetDef;
import pr2.generated.assets.AssetTypes.SymbolAssetDef;

final class AssetCatalog {
\tpublic static function media():Array<MediaAssetDef> {
\t\treturn """ + haxe_literal(media, 2) + """;
\t}

\tpublic static function symbols():Array<SymbolAssetDef> {
\t\treturn """ + haxe_literal(symbols, 2) + """;
\t}

\tpublic static function linkageClasses():Array<String> {
\t\treturn """ + haxe_literal(linkage_classes, 2) + """;
\t}

\tprivate function new() {}
}
"""


def parse_args(argv):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--xfl-dir", default=DEFAULT_XFL_DIR, help=f"default: {DEFAULT_XFL_DIR}")
    parser.add_argument("--out-dir", default=DEFAULT_OUT_DIR, help=f"default: {DEFAULT_OUT_DIR}")
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv or sys.argv[1:])

    try:
        metadata = build_metadata(args.xfl_dir)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    write_file(os.path.join(args.out_dir, "AssetTypes.hx"), schema_source())
    write_file(os.path.join(args.out_dir, "AssetConstants.hx"), constants_source(metadata))
    write_file(os.path.join(args.out_dir, "AssetCatalog.hx"), catalog_source(metadata))

    counts = metadata["counts"]
    print(
        "Generated Haxe asset catalog: "
        f"{counts['symbolFiles']} symbols, {counts['media']} media items, "
        f"{counts['timelineFrames']} timeline frames"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
