#!/usr/bin/env python3
"""
Generate a JSFL batch script that asks Adobe Animate to export PR2 SVG assets.

The generated JSFL consumes the machine-readable vector art inventory created
by tools/vector_art_inventory.py. It is intentionally a generated artifact so
we can run small proof batches before exporting every character channel.
"""

import argparse
import json
import os
import sys
from pathlib import Path


DEFAULT_MANIFEST = os.path.join("docs", "vector-art-inventory.json")
DEFAULT_OUT = os.path.join("export", "vector-art", "export-character-svg.jsfl")
DEFAULT_SVG_DIR = os.path.join("export", "vector-art", "svg")
DEFAULT_FLA = os.path.join("flash", "platform-racing-2.fla")
DEFAULT_ADOBE_SVG_EXPORTER = (
    "/Applications/Adobe Animate 2024/Adobe Animate 2024.app/Contents/Common/"
    "Configuration/Extensions/ExportSVG/jsfl/Export SVG.jsfl"
)


def file_uri(path):
    return Path(path).resolve().as_uri()


def js_string(value):
    return json.dumps(value)


def load_jobs(manifest_path, channels, kinds, limit):
    with open(manifest_path, encoding="utf-8") as handle:
        manifest = json.load(handle)

    channel_sources = {}
    for entry in manifest["characterExports"]:
        key = (entry["kind"], entry["id"], entry["channel"])
        channel_sources[key] = entry["source"].get("symbolName")

    jobs = []
    for entry in manifest["characterExports"]:
        if channels and entry["channel"] not in channels:
            continue
        if kinds and entry["kind"] not in kinds:
            continue
        source = entry["source"]
        source_symbol = source.get("symbolName")
        overlays = []
        if entry["channel"] in ("primary", "secondary") and source_symbol:
            export_symbol = source_symbol
            hidden_instances = []
            hidden_layers = []
        else:
            export_symbol = source["containerSymbol"]
            hidden_instances = ["colorMC", "colorMC2"] if entry["channel"] in ("static", "composite") else []
            hidden_layers = ["colorMC", "colorMC2"] if entry["channel"] in ("static", "composite") else []
            if entry["channel"] == "composite":
                for overlay_channel in ("primary", "secondary"):
                    overlay_symbol = channel_sources.get((entry["kind"], entry["id"], overlay_channel))
                    if overlay_symbol:
                        overlays.append(
                            {
                                "channel": overlay_channel,
                                "symbolName": overlay_symbol,
                                "frame": entry["frame"],
                            }
                        )

        jobs.append(
            {
                "id": entry["id"],
                "kind": entry["kind"],
                "name": entry["name"],
                "channel": entry["channel"],
                "frame": entry["frame"],
                "exportPath": entry["exportPath"],
                "symbolName": export_symbol,
                "hiddenInstances": hidden_instances,
                "hiddenLayers": hidden_layers,
                "overlays": overlays,
            }
        )

    if limit is not None:
        jobs = jobs[:limit]
    return jobs


def output_jobs(jobs, svg_dir):
    root = Path(svg_dir).resolve()
    records = []
    for job in jobs:
        record = dict(job)
        record["outputUri"] = (root / job["exportPath"]).as_uri()
        records.append(record)
    return records


def jsfl_source(jobs, fla_uri, svg_exporter_uri):
    return f"""// Generated by tools/generate_animate_svg_export_jsfl.py. Do not edit by hand.
// Open this file with Adobe Animate to export SVG assets.

var SOURCE_FLA_URI = {js_string(fla_uri)};
var ADOBE_SVG_EXPORTER_URI = {js_string(svg_exporter_uri)};
var JOBS = {json.dumps(jobs, indent=2, sort_keys=True)};

function log(message) {{
\tfl.trace("[PR2 SVG Export] " + message);
}}

function dirname(uri) {{
\treturn uri.replace(/\\/[^\\/]*$/, "");
}}

function mkdirs(uri) {{
\tvar parts = uri.split("/");
\tif (parts.length < 4) {{
\t\treturn;
\t}}
\tvar current = parts[0] + "//" + parts[2];
\tfor (var i = 3; i < parts.length; i++) {{
\t\tcurrent += "/" + parts[i];
\t\tif (!FLfile.exists(current)) {{
\t\t\tFLfile.createFolder(current);
\t\t}}
\t}}
}}

function selectFrame(timeline, frameIndex) {{
\ttry {{
\t\ttimeline.currentFrame = frameIndex;
\t}} catch (e) {{
\t}}
\ttry {{
\t\ttimeline.setSelectedFrames(frameIndex, frameIndex + 1, true);
\t}} catch (e) {{
\t}}
}}

function contains(values, value) {{
\tfor (var i = 0; i < values.length; i++) {{
\t\tif (values[i] == value) {{
\t\t\treturn true;
\t\t}}
\t}}
\treturn false;
}}

function setElementVisibility(elements, hiddenNames, hiddenStates) {{
\tif (!elements) {{
\t\treturn;
\t}}
\tfor (var i = 0; i < elements.length; i++) {{
\t\tvar element = elements[i];
\t\tif (element.name && contains(hiddenNames, element.name)) {{
\t\t\thiddenStates.push({{ target: element, visible: element.visible }});
\t\t\telement.visible = false;
\t\t}}
\t}}
}}

function setElementNamesVisible(elements, names, visible) {{
\tif (!elements) {{
\t\treturn;
\t}}
\tfor (var i = 0; i < elements.length; i++) {{
\t\tvar element = elements[i];
\t\tif (element.name && contains(names, element.name)) {{
\t\t\telement.visible = visible;
\t\t}}
\t}}
}}

function setLibraryVisibility(timeline, job, visible) {{
\tfor (var i = 0; i < timeline.layers.length; i++) {{
\t\tvar layer = timeline.layers[i];
\t\tif (contains(job.hiddenLayers, layer.name)) {{
\t\t\tlayer.visible = visible;
\t\t}}
\t\tfor (var f = 0; f < layer.frames.length; f++) {{
\t\t\tsetElementNamesVisible(layer.frames[f].elements, job.hiddenInstances, visible);
\t\t}}
\t}}
}}

function prepareLibraryItem(doc, job) {{
\tif (!doc.library.editItem(job.symbolName)) {{
\t\tthrow new Error("Could not edit library item: " + job.symbolName);
\t}}
\tvar editDoc = fl.getDocumentDOM();
\tvar timeline = editDoc.getTimeline();
\tselectFrame(timeline, job.frame);
\tsetLibraryVisibility(timeline, job, false);
\teditDoc.exitEditMode();
}}

function restoreLibraryItem(doc, job) {{
\tif (job.hiddenLayers.length == 0 && job.hiddenInstances.length == 0) {{
\t\treturn;
\t}}
\tif (!doc.library.editItem(job.symbolName)) {{
\t\tthrow new Error("Could not re-edit library item for restore: " + job.symbolName);
\t}}
\tvar editDoc = fl.getDocumentDOM();
\tvar timeline = editDoc.getTimeline();
\tsetLibraryVisibility(timeline, job, true);
\teditDoc.exitEditMode();
}}

function exportCurrentView(outputUri) {{
\tmkdirs(dirname(outputUri));
\t// Signature used by Animate's own Export SVG panel:
\t// exportSVG(basePath, filePath, embed, folder, hiddenLayers, optimizeForCH, startFrame, endFrame)
\tfl.runScript(ADOBE_SVG_EXPORTER_URI, "exportSVG", "", outputUri, true, "", false, false, 0, 0);
}}

function stageSymbol(doc, symbolName, frame) {{
\tdoc.library.addItemToDocument({{ x: 0, y: 0 }}, symbolName);
\tvar instance = doc.selection && doc.selection.length > 0 ? doc.selection[0] : null;
\tif (!instance) {{
\t\tthrow new Error("Could not stage library item: " + symbolName);
\t}}
\ttry {{
\t\tinstance.symbolType = "graphic";
\t}} catch (e) {{
\t}}
\ttry {{
\t\tinstance.firstFrame = frame;
\t}} catch (e) {{
\t}}
\ttry {{
\t\tinstance.loop = "single frame";
\t}} catch (e) {{
\t}}
}}

function exportJob(doc, job) {{
\tlog("exporting " + job.exportPath + " from " + job.symbolName + " frame " + job.frame);
\tprepareLibraryItem(doc, job);
\tdoc = fl.getDocumentDOM();
\ttry {{
\t\tdoc.selectAll();
\t\tdoc.deleteSelection();
\t}} catch (e) {{
\t}}
\tstageSymbol(doc, job.symbolName, job.frame);
\tfor (var i = 0; i < job.overlays.length; i++) {{
\t\tstageSymbol(doc, job.overlays[i].symbolName, job.overlays[i].frame);
\t}}
\texportCurrentView(job.outputUri);
\ttry {{
\t\tdoc.selectAll();
\t\tdoc.deleteSelection();
\t}} catch (e) {{
\t}}
\trestoreLibraryItem(doc, job);
}}

function run() {{
\tlog("opening " + SOURCE_FLA_URI);
\tvar doc = fl.openDocument(SOURCE_FLA_URI);
\tif (!doc) {{
\t\tthrow new Error("Could not open source FLA: " + SOURCE_FLA_URI);
\t}}
\tfor (var i = 0; i < JOBS.length; i++) {{
\t\texportJob(doc, JOBS[i]);
\t}}
\tlog("complete: " + JOBS.length + " SVG exports");
}}

run();
"""


def parse_args(argv):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", default=DEFAULT_MANIFEST, help=f"default: {DEFAULT_MANIFEST}")
    parser.add_argument("--fla", default=DEFAULT_FLA, help=f"default: {DEFAULT_FLA}")
    parser.add_argument("--svg-dir", default=DEFAULT_SVG_DIR, help=f"default: {DEFAULT_SVG_DIR}")
    parser.add_argument("--out", default=DEFAULT_OUT, help=f"default: {DEFAULT_OUT}; use - for stdout")
    parser.add_argument("--svg-exporter", default=DEFAULT_ADOBE_SVG_EXPORTER, help="Animate Export SVG.jsfl path")
    parser.add_argument("--limit", type=int, help="only include the first N matching jobs")
    parser.add_argument("--channel", action="append", choices=("static", "primary", "secondary", "composite"), help="repeatable channel filter")
    parser.add_argument("--kind", action="append", choices=("hat", "head", "body", "feet"), help="repeatable character kind filter")
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv or sys.argv[1:])
    jobs = output_jobs(load_jobs(args.manifest, args.channel, args.kind, args.limit), args.svg_dir)
    source = jsfl_source(jobs, file_uri(args.fla), file_uri(args.svg_exporter))

    if args.out == "-":
        print(source, end="")
    else:
        os.makedirs(os.path.dirname(args.out), exist_ok=True)
        with open(args.out, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(source)

    print(f"wrote {len(jobs)} export jobs", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
