package pr2;

import pr2.audio.AudioRuntimeTest;
import pr2.audio.AudioUnlockGateTest;
import pr2.app.FatalErrorReporterTest;
import pr2.app.ScreenTest;
import pr2.character.CharacterAtlasTest;
import pr2.crypto.ARC4CompatTest;
import pr2.crypto.HurlantSymmetricCompatTest;
import pr2.crypto.HurlantUtilCompatTest;
import pr2.crypto.MD5CompatTest;
import pr2.crypto.PR2EncryptorTest;
import pr2.crypto.RandomCompatTest;
import pr2.data.DataCompatTest;
import pr2.data.JiggminRandomCompatTest;
import pr2.data.ObjectsCompatTest;
import pr2.data.SWFStatsTest;
import pr2.data.SecureDataCompatTest;
import pr2.data.SettingsCompatTest;
import pr2.data.TimeCompatTest;
import pr2.display.RemovableTest;
import pr2.effects.PixelEffect1Test;
import pr2.effects.PhysicsEffectTest;
import pr2.effects.ShotEffectTest;
import pr2.effects.SlashTest;
import pr2.effects.TeleportPopTest;
import pr2.gameplay.CameraFollowTest;
import pr2.gameplay.CatCaptchaTest;
import pr2.gameplay.CountdownTest;
import pr2.gameplay.CourseTimerTest;
import pr2.gameplay.DrawingInfoTest;
import pr2.gameplay.FinishedPageTest;
import pr2.gameplay.GameCommandShellTest;
import pr2.gameplay.GameShellMountTest;
import pr2.gameplay.HeartsTest;
import pr2.gameplay.ItemDisplayTest;
import pr2.gameplay.LevelConfigTest;
import pr2.gameplay.LevelEntryStateTest;
import pr2.gameplay.MiniMapTest;
import pr2.gameplay.ModesTest;
import pr2.gameplay.RoguelikeModeTest;
import pr2.gameplay.MusicSelectionTest;
import pr2.gameplay.PlaceArtifactTest;
import pr2.gameplay.PrizePopupTest;
import pr2.gameplay.QuitButtonTest;
import pr2.gameplay.RaceChatTest;
import pr2.gameplay.RaceSessionTranscriptTest;
import pr2.gameplay.RotationMathTest;
import pr2.gameplay.SpecialEventTest;
import pr2.gameplay.SpectatePickerTest;
import pr2.gameplay.StatsDisplayTest;
import pr2.graphics.JPEGEncoderCompatTest;
import pr2.harness.PlayerDisplayPlacementTest;
import pr2.level.WorldLevelParserTest;
import pr2.level.ServerLevelDecoderTest;
import pr2.level.ServerLevelWorldAdapterTest;
import pr2.level.ServerLevelRendererTest;
import pr2.runtime.EpicFlashTest;
import pr2.runtime.FlButtonTest;
import pr2.runtime.FlComponentsTest;
import pr2.runtime.FlattenSafetyGateTest;
import pr2.runtime.PR2MovieClipRuntimeTest;
import pr2.runtime.StaticSubtreeAnalyzerTest;
import pr2.ui.EmblemLoaderTest;
import pr2.ui.GuildNameTest;
import pr2.ui.GpNotificationTest;
import pr2.ui.PageNavigationFocusTest;
import pr2.ui.SelectableButtonTest;
import pr2.util.AsyncRemovalGuardTest;

class DeterministicShard3 {
	public static function main():Void {
		AudioUnlockGateTest.main();
		AudioRuntimeTest.main();
		FatalErrorReporterTest.main();
		ScreenTest.main();
		PR2MovieClipRuntimeTest.main();
		StaticSubtreeAnalyzerTest.main();
		FlattenSafetyGateTest.main();
		FlButtonTest.main();
		FlComponentsTest.main();
		EpicFlashTest.main();
		GpNotificationTest.main();
		EmblemLoaderTest.main();
		GuildNameTest.main();
		SelectableButtonTest.main();
		PageNavigationFocusTest.main();
		AsyncRemovalGuardTest.main();
		RemovableTest.main();
		PixelEffect1Test.main();
		PhysicsEffectTest.main();
		ShotEffectTest.main();
		SlashTest.main();
		TeleportPopTest.main();
		CharacterAtlasTest.main();
		PR2EncryptorTest.main();
		MD5CompatTest.main();
		ARC4CompatTest.main();
		RandomCompatTest.main();
		HurlantSymmetricCompatTest.main();
		HurlantUtilCompatTest.main();
		DataCompatTest.main();
		JiggminRandomCompatTest.main();
		ObjectsCompatTest.main();
		SecureDataCompatTest.main();
		SettingsCompatTest.main();
		SWFStatsTest.main();
		TimeCompatTest.main();
		WorldLevelParserTest.main();
		ServerLevelDecoderTest.main();
		ServerLevelWorldAdapterTest.main();
		ServerLevelRendererTest.main();
		CameraFollowTest.main();
		PlayerDisplayPlacementTest.main();
		RotationMathTest.main();
		MiniMapTest.main();
		ItemDisplayTest.main();
		MusicSelectionTest.main();
		RaceChatTest.main();
		DrawingInfoTest.main();
		FinishedPageTest.main();
		HeartsTest.main();
		StatsDisplayTest.main();
		CountdownTest.main();
		CourseTimerTest.main();
		CatCaptchaTest.main();
		PrizePopupTest.main();
		SpectatePickerTest.main();
		SpecialEventTest.main();
		PlaceArtifactTest.main();
		ModesTest.main();
		RoguelikeModeTest.main();
		JPEGEncoderCompatTest.main();
		LevelConfigTest.main();
		GameShellMountTest.main();
		LevelEntryStateTest.main();
		GameCommandShellTest.main();
		QuitButtonTest.main();
		RaceSessionTranscriptTest.main();
		trace("DeterministicShard3 passed");
		Sys.exit(0);
	}
}
