package pr2;

import pr2.lobby.AccountTabTest;
import pr2.lobby.ArtifactHintClientTest;
import pr2.lobby.AutoDismissPopupTest;
import pr2.lobby.ChangePasswordPopupTest;
import pr2.lobby.ChatTabTest;
import pr2.lobby.ColorPickerTest;
import pr2.lobby.CreateGuildPopupTest;
import pr2.lobby.CreditsPopupTest;
import pr2.lobby.DiscordVerificationPopupTest;
import pr2.lobby.ExternalLinkPopupTest;
import pr2.lobby.GuildJoinPopupTest;
import pr2.lobby.GuildPopupTest;
import pr2.lobby.HtmlNameMakerTest;
import pr2.lobby.HatsMenuTest;
import pr2.lobby.ItemMenuTest;
import pr2.lobby.LevelInfoPopupTest;
import pr2.lobby.LobbySessionTest;
import pr2.lobby.LogoutPassPopupTest;
import pr2.lobby.LobbyServicesTest;
import pr2.lobby.MessagesItemTest;
import pr2.lobby.OptionsPopupTest;
import pr2.lobby.OutfitPopupTest;
import pr2.lobby.PMRFCodesPopupTest;
import pr2.lobby.PlayerPopupTest;
import pr2.lobby.SendMessagePopupTest;
import pr2.lobby.SetEmailPopupTest;
import pr2.lobby.StorePopupTest;
import pr2.lobby.TransferGuildPopupTest;
import pr2.lobby.UploadingPopupTest;
import pr2.net.AccountCreationClientTest;
import pr2.net.CampaignListClientTest;
import pr2.net.CommAuthTest;
import pr2.net.ForgotPasswordClientTest;
import pr2.net.JsonClientTest;
import pr2.net.LevelDataClientTest;
import pr2.net.LobbySocketLifecycleTest;
import pr2.net.LoginAuthClientTest;
import pr2.net.LoginSessionGateTest;
import pr2.net.LoginSocketProtocolTest;
import pr2.net.SavedAccountsTest;
import pr2.net.ServerConfigTest;
import pr2.net.ServerStatusClientTest;
import pr2.net.SuperLoaderTest;
import pr2.page.CampaignTestScreenTest;
import pr2.page.EditorBlockOptionsTest;
import pr2.page.EditorSettingsTest;

class DeterministicShard4 {
	public static function main():Void {
		ServerConfigTest.main();
		CommAuthTest.main();
		ServerStatusClientTest.main();
		LoginSocketProtocolTest.main();
		LobbySocketLifecycleTest.main();
		LoginSessionGateTest.main();
		SavedAccountsTest.main();
		SuperLoaderTest.main();
		CampaignListClientTest.main();
		AccountCreationClientTest.main();
		ForgotPasswordClientTest.main();
		LoginAuthClientTest.main();
		LevelDataClientTest.main();
		JsonClientTest.main();
		EditorBlockOptionsTest.main();
		EditorSettingsTest.main();
		CampaignTestScreenTest.main();
		ArtifactHintClientTest.main();
		AutoDismissPopupTest.main();
		LobbySessionTest.main();
		LobbyServicesTest.main();
		AccountTabTest.main();
		ChatTabTest.main();
		ChangePasswordPopupTest.main();
		ColorPickerTest.main();
		CreateGuildPopupTest.main();
		CreditsPopupTest.main();
		DiscordVerificationPopupTest.main();
		ExternalLinkPopupTest.main();
		GuildPopupTest.main();
		GuildJoinPopupTest.main();
		HatsMenuTest.main();
		HtmlNameMakerTest.main();
		ItemMenuTest.main();
		LevelInfoPopupTest.main();
		LogoutPassPopupTest.main();
		MessagesItemTest.main();
		OptionsPopupTest.main();
		OutfitPopupTest.main();
		PMRFCodesPopupTest.main();
		PlayerPopupTest.main();
		SendMessagePopupTest.main();
		SetEmailPopupTest.main();
		StorePopupTest.main();
		TransferGuildPopupTest.main();
		UploadingPopupTest.main();
		trace("DeterministicShard4 passed");
		Sys.exit(0);
	}
}
