package pr2;

import pr2.audio.AudioUnlockGateTest;
import pr2.audio.AudioRuntimeTest;
import pr2.app.FatalErrorReporterTest;
import pr2.app.ScreenTest;
import pr2.character.CharacterAtlasTest;
import pr2.character.CharacterBaseTest;
import pr2.character.CharacterDisplayTest;
import pr2.character.CharacterStateTest;
import pr2.character.LocalCharacterEmitTest;
import pr2.character.LocalCharacterTest;
import pr2.character.ParticleEmitterTest;
import pr2.character.RemoteCharacterConsumeTest;
import pr2.crypto.PR2EncryptorTest;
import pr2.crypto.MD5CompatTest;
import pr2.crypto.ARC4CompatTest;
import pr2.crypto.RandomCompatTest;
import pr2.crypto.HurlantSymmetricCompatTest;
import pr2.crypto.HurlantUtilCompatTest;
import pr2.data.DataCompatTest;
import pr2.data.JiggminRandomCompatTest;
import pr2.data.ObjectsCompatTest;
import pr2.data.SecureDataCompatTest;
import pr2.data.SettingsCompatTest;
import pr2.data.SWFStatsTest;
import pr2.data.TimeCompatTest;
import pr2.display.RemovableTest;
import pr2.effects.PixelEffect1Test;
import pr2.effects.PhysicsEffectTest;
import pr2.effects.ShotEffectTest;
import pr2.effects.SlashTest;
import pr2.effects.TeleportPopTest;
import pr2.gameplay.player.LocalPlayerControllerTest;
import pr2.gameplay.player.PlayerDisplayPlacementTest;
import pr2.gameplay.RotationMathTest;
import pr2.gameplay.MiniMapTest;
import pr2.gameplay.ItemDisplayTest;
import pr2.gameplay.MusicSelectionTest;
import pr2.gameplay.RaceChatTest;
import pr2.gameplay.DrawingInfoTest;
import pr2.gameplay.FinishedPageTest;
import pr2.gameplay.HeartsTest;
import pr2.gameplay.StatsDisplayTest;
import pr2.gameplay.CountdownTest;
import pr2.gameplay.CourseTimerTest;
import pr2.gameplay.CatCaptchaTest;
import pr2.gameplay.PrizePopupTest;
import pr2.gameplay.SpectatePickerTest;
import pr2.gameplay.SpecialEventTest;
import pr2.gameplay.PlaceArtifactTest;
import pr2.gameplay.LevelConfigTest;
import pr2.gameplay.ModesTest;
import pr2.gameplay.RoguelikeModeTest;
import pr2.graphics.JPEGEncoderCompatTest;
import pr2.gameplay.GameShellMountTest;
import pr2.gameplay.CharacterLifecycleTest;
import pr2.gameplay.MultiplayerRaceStageTest;
import pr2.gameplay.LevelEntryStateTest;
import pr2.gameplay.GameCommandShellTest;
import pr2.gameplay.QuitButtonTest;
import pr2.gameplay.RaceSessionTranscriptTest;
import pr2.level.WorldLevelParserTest;
import pr2.lobby.LobbyServicesTest;
import pr2.lobby.AccountTabTest;
import pr2.lobby.ArtifactHintClientTest;
import pr2.lobby.AutoDismissPopupTest;
import pr2.lobby.ChatTabTest;
import pr2.lobby.ChangePasswordPopupTest;
import pr2.lobby.ColorPickerTest;
import pr2.lobby.CreateGuildPopupTest;
import pr2.lobby.CreditsPopupTest;
import pr2.lobby.DiscordVerificationPopupTest;
import pr2.lobby.ExternalLinkPopupTest;
import pr2.lobby.GuildPopupTest;
import pr2.lobby.GuildJoinPopupTest;
import pr2.lobby.HatsMenuTest;
import pr2.lobby.HtmlNameMakerTest;
import pr2.lobby.ItemMenuTest;
import pr2.lobby.LevelInfoPopupTest;
import pr2.lobby.LobbySessionTest;
import pr2.lobby.LogoutPassPopupTest;
import pr2.lobby.MessagesItemTest;
import pr2.lobby.MobileLobbyLayoutTest;
import pr2.lobby.OptionsPopupTest;
import pr2.lobby.PMRFCodesPopupTest;
import pr2.lobby.PlayerPopupTest;
import pr2.lobby.SendMessagePopupTest;
import pr2.lobby.SetEmailPopupTest;
import pr2.lobby.StorePopupTest;
import pr2.lobby.TransferGuildPopupTest;
import pr2.lobby.UploadingPopupTest;
import pr2.level.ServerLevelDecoderTest;
import pr2.level.ServerLevelWorldAdapterTest;
import pr2.level.ServerLevelRendererTest;
import pr2.gameplay.CameraFollowTest;
import pr2.net.AccountCreationClientTest;
import pr2.net.ForgotPasswordClientTest;
import pr2.net.CampaignListClientTest;
import pr2.net.CommAuthTest;
import pr2.net.LevelDataClientTest;
import pr2.net.JsonClientTest;
import pr2.net.LoginAuthClientTest;
import pr2.net.LoginSocketProtocolTest;
import pr2.net.LobbySocketLifecycleTest;
import pr2.net.LoginSessionGateTest;
import pr2.net.SavedAccountsTest;
import pr2.net.ServerConfigTest;
import pr2.net.ServerStatusClientTest;
import pr2.net.SuperLoaderTest;
import pr2.page.EditorBlockOptionsTest;
import pr2.page.EditorSettingsTest;
import pr2.page.CampaignTestScreenTest;
import pr2.runtime.FlButtonTest;
import pr2.runtime.FlComponentsTest;
import pr2.runtime.EpicFlashTest;
import pr2.runtime.PR2MovieClipRuntimeTest;
import pr2.runtime.StaticSubtreeAnalyzerTest;
import pr2.runtime.FlattenSafetyGateTest;
import pr2.runtime.SvgAssetTest;
import pr2.ui.EmblemLoaderTest;
import pr2.ui.GuildNameTest;
import pr2.ui.GpNotificationTest;
import pr2.ui.PageNavigationFocusTest;
import pr2.ui.SelectableButtonTest;
import pr2.util.AsyncRemovalGuardTest;

class DeterministicTestSuite {
	public static function main():Void {
		DeterministicTestMode.runSuite("AudioUnlockGateTest", ["audio"], AudioUnlockGateTest.main);
		DeterministicTestMode.runSuite("AudioRuntimeTest", ["audio"], AudioRuntimeTest.main);
		DeterministicTestMode.runSuite("FatalErrorReporterTest", ["runtime"], FatalErrorReporterTest.main);
		DeterministicTestMode.runSuite("ScreenTest", ["runtime"], ScreenTest.main);
		DeterministicTestMode.runSuite("PR2MovieClipRuntimeTest", ["runtime"], PR2MovieClipRuntimeTest.main);
		DeterministicTestMode.runSuite("StaticSubtreeAnalyzerTest", ["runtime"], StaticSubtreeAnalyzerTest.main);
		DeterministicTestMode.runSuite("FlattenSafetyGateTest", ["runtime"], FlattenSafetyGateTest.main);
		DeterministicTestMode.runSuite("FlButtonTest", ["runtime"], FlButtonTest.main);
		DeterministicTestMode.runSuite("FlComponentsTest", ["runtime"], FlComponentsTest.main);
		DeterministicTestMode.runSuite("EpicFlashTest", ["runtime"], EpicFlashTest.main);
		DeterministicTestMode.runSuite("SvgAssetTest", ["runtime", "ui", "character", "level-rendering"], SvgAssetTest.main);
		DeterministicTestMode.runSuite("GpNotificationTest", ["ui"], GpNotificationTest.main);
		DeterministicTestMode.runSuite("EmblemLoaderTest", ["ui"], EmblemLoaderTest.main);
		DeterministicTestMode.runSuite("GuildNameTest", ["ui"], GuildNameTest.main);
		DeterministicTestMode.runSuite("SelectableButtonTest", ["ui"], SelectableButtonTest.main);
		DeterministicTestMode.runSuite("PageNavigationFocusTest", ["ui"], PageNavigationFocusTest.main);
		DeterministicTestMode.runSuite("AsyncRemovalGuardTest", ["runtime"], AsyncRemovalGuardTest.main);
		DeterministicTestMode.runSuite("RemovableTest", ["runtime"], RemovableTest.main);
		DeterministicTestMode.runSuite("PixelEffect1Test", ["effects"], PixelEffect1Test.main);
		DeterministicTestMode.runSuite("PhysicsEffectTest", ["effects", "physics"], PhysicsEffectTest.main);
		DeterministicTestMode.runSuite("ShotEffectTest", ["effects"], ShotEffectTest.main);
		DeterministicTestMode.runSuite("SlashTest", ["effects"], SlashTest.main);
		DeterministicTestMode.runSuite("TeleportPopTest", ["effects"], TeleportPopTest.main);
		DeterministicTestMode.runSuite("CharacterAtlasTest", ["character"], CharacterAtlasTest.main);
		DeterministicTestMode.runSuite("CharacterBaseTest", ["character"], CharacterBaseTest.main);
		DeterministicTestMode.runSuite("CharacterDisplayTest", ["character", "items"], CharacterDisplayTest.main);
		DeterministicTestMode.runSuite("CharacterStateTest", ["character", "physics"], CharacterStateTest.main);
		DeterministicTestMode.runSuite("LocalCharacterTest", ["character", "physics", "items"], LocalCharacterTest.main);
		DeterministicTestMode.runSuite("LocalCharacterEmitTest", ["character", "physics", "network"], LocalCharacterEmitTest.main);
		DeterministicTestMode.runSuite("ParticleEmitterTest", ["character"], ParticleEmitterTest.main);
		DeterministicTestMode.runSuite("RemoteCharacterConsumeTest", ["character", "physics", "network"], RemoteCharacterConsumeTest.main);
		DeterministicTestMode.runSuite("PR2EncryptorTest", ["crypto"], PR2EncryptorTest.main);
		DeterministicTestMode.runSuite("MD5CompatTest", ["crypto"], MD5CompatTest.main);
		DeterministicTestMode.runSuite("ARC4CompatTest", ["crypto"], ARC4CompatTest.main);
		DeterministicTestMode.runSuite("RandomCompatTest", ["crypto"], RandomCompatTest.main);
		DeterministicTestMode.runSuite("HurlantSymmetricCompatTest", ["crypto"], HurlantSymmetricCompatTest.main);
		DeterministicTestMode.runSuite("HurlantUtilCompatTest", ["crypto"], HurlantUtilCompatTest.main);
		DeterministicTestMode.runSuite("DataCompatTest", ["data"], DataCompatTest.main);
		DeterministicTestMode.runSuite("JiggminRandomCompatTest", ["data"], JiggminRandomCompatTest.main);
		DeterministicTestMode.runSuite("ObjectsCompatTest", ["data"], ObjectsCompatTest.main);
		DeterministicTestMode.runSuite("SecureDataCompatTest", ["data"], SecureDataCompatTest.main);
		DeterministicTestMode.runSuite("SettingsCompatTest", ["data"], SettingsCompatTest.main);
		DeterministicTestMode.runSuite("SWFStatsTest", ["data"], SWFStatsTest.main);
		DeterministicTestMode.runSuite("TimeCompatTest", ["data"], TimeCompatTest.main);
		DeterministicTestMode.runSuite("WorldLevelParserTest", ["level-rendering", "blocks"], WorldLevelParserTest.main);
		DeterministicTestMode.runSuite("ServerLevelDecoderTest", ["level-rendering", "blocks"], ServerLevelDecoderTest.main);
		DeterministicTestMode.runSuite("ServerLevelWorldAdapterTest", ["level-rendering", "blocks"], ServerLevelWorldAdapterTest.main);
		DeterministicTestMode.runSuite("ServerLevelRendererTest", ["level-rendering", "blocks"], ServerLevelRendererTest.main);
		DeterministicTestMode.runSuite("CameraFollowTest", ["gameplay", "physics", "level-rendering"], CameraFollowTest.main);
		DeterministicTestMode.runSuite("PlayerDisplayPlacementTest", ["gameplay", "physics"], PlayerDisplayPlacementTest.main);
		DeterministicTestMode.runSuite("LocalPlayerControllerTest", ["gameplay", "physics", "blocks", "items"], LocalPlayerControllerTest.main);
		DeterministicTestMode.runSuite("RotationMathTest", ["gameplay", "physics"], RotationMathTest.main);
		DeterministicTestMode.runSuite("MiniMapTest", ["gameplay", "level-rendering"], MiniMapTest.main);
		DeterministicTestMode.runSuite("ItemDisplayTest", ["gameplay", "items"], ItemDisplayTest.main);
		DeterministicTestMode.runSuite("MusicSelectionTest", ["gameplay"], MusicSelectionTest.main);
		DeterministicTestMode.runSuite("RaceChatTest", ["gameplay"], RaceChatTest.main);
		DeterministicTestMode.runSuite("DrawingInfoTest", ["gameplay", "level-rendering"], DrawingInfoTest.main);
		DeterministicTestMode.runSuite("FinishedPageTest", ["gameplay"], FinishedPageTest.main);
		DeterministicTestMode.runSuite("HeartsTest", ["gameplay"], HeartsTest.main);
		DeterministicTestMode.runSuite("StatsDisplayTest", ["gameplay"], StatsDisplayTest.main);
		DeterministicTestMode.runSuite("CountdownTest", ["gameplay"], CountdownTest.main);
		DeterministicTestMode.runSuite("CourseTimerTest", ["gameplay"], CourseTimerTest.main);
		DeterministicTestMode.runSuite("CatCaptchaTest", ["gameplay"], CatCaptchaTest.main);
		DeterministicTestMode.runSuite("PrizePopupTest", ["gameplay", "items"], PrizePopupTest.main);
		DeterministicTestMode.runSuite("SpectatePickerTest", ["gameplay"], SpectatePickerTest.main);
		DeterministicTestMode.runSuite("SpecialEventTest", ["gameplay"], SpecialEventTest.main);
		DeterministicTestMode.runSuite("PlaceArtifactTest", ["gameplay"], PlaceArtifactTest.main);
		DeterministicTestMode.runSuite("ModesTest", ["gameplay"], ModesTest.main);
		DeterministicTestMode.runSuite("RoguelikeModeTest", ["gameplay"], RoguelikeModeTest.main);
		DeterministicTestMode.runSuite("JPEGEncoderCompatTest", ["runtime"], JPEGEncoderCompatTest.main);
		DeterministicTestMode.runSuite("LevelConfigTest", ["gameplay", "level-rendering", "blocks"], LevelConfigTest.main);
		DeterministicTestMode.runSuite("GameShellMountTest", ["gameplay", "physics", "level-rendering", "blocks", "items"], GameShellMountTest.main);
		DeterministicTestMode.runSuite("CharacterLifecycleTest", ["gameplay", "physics", "network"], CharacterLifecycleTest.main);
		DeterministicTestMode.runSuite("MultiplayerRaceStageTest", ["gameplay", "physics", "blocks", "network"], MultiplayerRaceStageTest.main);
		DeterministicTestMode.runSuite("LevelEntryStateTest", ["gameplay"], LevelEntryStateTest.main);
		DeterministicTestMode.runSuite("GameCommandShellTest", ["gameplay"], GameCommandShellTest.main);
		DeterministicTestMode.runSuite("QuitButtonTest", ["gameplay"], QuitButtonTest.main);
		DeterministicTestMode.runSuite("RaceSessionTranscriptTest", ["gameplay"], RaceSessionTranscriptTest.main);
		DeterministicTestMode.runSuite("ServerConfigTest", ["network"], ServerConfigTest.main);
		DeterministicTestMode.runSuite("CommAuthTest", ["network"], CommAuthTest.main);
		DeterministicTestMode.runSuite("ServerStatusClientTest", ["network"], ServerStatusClientTest.main);
		DeterministicTestMode.runSuite("LoginSocketProtocolTest", ["network"], LoginSocketProtocolTest.main);
		DeterministicTestMode.runSuite("LobbySocketLifecycleTest", ["network", "lobby"], LobbySocketLifecycleTest.main);
		DeterministicTestMode.runSuite("LoginSessionGateTest", ["network"], LoginSessionGateTest.main);
		DeterministicTestMode.runSuite("SavedAccountsTest", ["network"], SavedAccountsTest.main);
		DeterministicTestMode.runSuite("SuperLoaderTest", ["network"], SuperLoaderTest.main);
		DeterministicTestMode.runSuite("CampaignListClientTest", ["network", "lobby"], CampaignListClientTest.main);
		DeterministicTestMode.runSuite("AccountCreationClientTest", ["network"], AccountCreationClientTest.main);
		DeterministicTestMode.runSuite("ForgotPasswordClientTest", ["network"], ForgotPasswordClientTest.main);
		DeterministicTestMode.runSuite("LoginAuthClientTest", ["network"], LoginAuthClientTest.main);
		DeterministicTestMode.runSuite("LevelDataClientTest", ["network"], LevelDataClientTest.main);
		DeterministicTestMode.runSuite("JsonClientTest", ["network"], JsonClientTest.main);
		DeterministicTestMode.runSuite("EditorBlockOptionsTest", ["level-editor"], EditorBlockOptionsTest.main);
		DeterministicTestMode.runSuite("EditorSettingsTest", ["level-editor"], EditorSettingsTest.main);
		DeterministicTestMode.runSuite("CampaignTestScreenTest", ["level-editor"], CampaignTestScreenTest.main);
		DeterministicTestMode.runSuite("ArtifactHintClientTest", ["lobby"], ArtifactHintClientTest.main);
		DeterministicTestMode.runSuite("AutoDismissPopupTest", ["lobby"], AutoDismissPopupTest.main);
		DeterministicTestMode.runSuite("LobbySessionTest", ["lobby"], LobbySessionTest.main);
		DeterministicTestMode.runSuite("LobbyServicesTest", ["lobby"], LobbyServicesTest.main);
		DeterministicTestMode.runSuite("AccountTabTest", ["lobby"], AccountTabTest.main);
		DeterministicTestMode.runSuite("ChatTabTest", ["lobby"], ChatTabTest.main);
		DeterministicTestMode.runSuite("ChangePasswordPopupTest", ["lobby"], ChangePasswordPopupTest.main);
		DeterministicTestMode.runSuite("ColorPickerTest", ["lobby"], ColorPickerTest.main);
		DeterministicTestMode.runSuite("CreateGuildPopupTest", ["lobby"], CreateGuildPopupTest.main);
		DeterministicTestMode.runSuite("CreditsPopupTest", ["lobby"], CreditsPopupTest.main);
		DeterministicTestMode.runSuite("DiscordVerificationPopupTest", ["lobby"], DiscordVerificationPopupTest.main);
		DeterministicTestMode.runSuite("ExternalLinkPopupTest", ["lobby"], ExternalLinkPopupTest.main);
		DeterministicTestMode.runSuite("GuildPopupTest", ["lobby"], GuildPopupTest.main);
		DeterministicTestMode.runSuite("GuildJoinPopupTest", ["lobby"], GuildJoinPopupTest.main);
		DeterministicTestMode.runSuite("HatsMenuTest", ["lobby", "items"], HatsMenuTest.main);
		DeterministicTestMode.runSuite("HtmlNameMakerTest", ["lobby"], HtmlNameMakerTest.main);
		DeterministicTestMode.runSuite("ItemMenuTest", ["lobby", "items"], ItemMenuTest.main);
		DeterministicTestMode.runSuite("LevelInfoPopupTest", ["lobby"], LevelInfoPopupTest.main);
		DeterministicTestMode.runSuite("LogoutPassPopupTest", ["lobby"], LogoutPassPopupTest.main);
		DeterministicTestMode.runSuite("MessagesItemTest", ["lobby"], MessagesItemTest.main);
		DeterministicTestMode.runSuite("MobileLobbyLayoutTest", ["lobby"], MobileLobbyLayoutTest.main);
		DeterministicTestMode.runSuite("OptionsPopupTest", ["lobby"], OptionsPopupTest.main);
		DeterministicTestMode.runSuite("PMRFCodesPopupTest", ["lobby"], PMRFCodesPopupTest.main);
		DeterministicTestMode.runSuite("PlayerPopupTest", ["lobby"], PlayerPopupTest.main);
		DeterministicTestMode.runSuite("SendMessagePopupTest", ["lobby"], SendMessagePopupTest.main);
		DeterministicTestMode.runSuite("SetEmailPopupTest", ["lobby"], SetEmailPopupTest.main);
		DeterministicTestMode.runSuite("StorePopupTest", ["lobby", "items"], StorePopupTest.main);
		DeterministicTestMode.runSuite("TransferGuildPopupTest", ["lobby"], TransferGuildPopupTest.main);
		DeterministicTestMode.runSuite("UploadingPopupTest", ["lobby"], UploadingPopupTest.main);
		if (DeterministicTestMode.hasGroupSelection()) {
			trace('DeterministicTestSuite selected run passed (${DeterministicTestMode.selectionSummary()})');
		} else if (DeterministicTestMode.isSmoke()) {
			trace("DeterministicTestSuite smoke run passed (123 suites)");
		} else {
			trace("DeterministicTestSuite passed");
		}
		// All assertions are synchronous, but pulling in openfl/lime leaves the
		// eval event loop alive, so the `--interp` process would otherwise hang
		// after main() returns instead of exiting. Terminate explicitly.
		Sys.exit(0);
	}
}
