package pr2;

import pr2.audio.AudioUnlockGateTest;
import pr2.audio.AudioRuntimeTest;
import pr2.app.FatalErrorReporterTest;
import pr2.app.ScreenTest;
import pr2.character.CharacterAtlasTest;
import pr2.character.CharacterBaseTest;
import pr2.character.CharacterDisplayTest;
import pr2.character.CharacterStateTest;
import pr2.character.LocalCharacterEmitTest;
import pr2.character.LocalCharacterTest;
import pr2.character.ParticleEmitterTest;
import pr2.character.RemoteCharacterConsumeTest;
import pr2.crypto.PR2EncryptorTest;
import pr2.crypto.MD5CompatTest;
import pr2.crypto.ARC4CompatTest;
import pr2.crypto.RandomCompatTest;
import pr2.crypto.HurlantSymmetricCompatTest;
import pr2.crypto.HurlantUtilCompatTest;
import pr2.data.DataCompatTest;
import pr2.data.JiggminRandomCompatTest;
import pr2.data.ObjectsCompatTest;
import pr2.data.SecureDataCompatTest;
import pr2.data.SettingsCompatTest;
import pr2.data.SWFStatsTest;
import pr2.data.TimeCompatTest;
import pr2.display.RemovableTest;
import pr2.effects.PixelEffect1Test;
import pr2.effects.PhysicsEffectTest;
import pr2.effects.ShotEffectTest;
import pr2.effects.SlashTest;
import pr2.effects.TeleportPopTest;
import pr2.harness.LocalPlayerControllerTest;
import pr2.harness.PlayerDisplayPlacementTest;
import pr2.gameplay.RotationMathTest;
import pr2.gameplay.MiniMapTest;
import pr2.gameplay.ItemDisplayTest;
import pr2.gameplay.MusicSelectionTest;
import pr2.gameplay.RaceChatTest;
import pr2.gameplay.DrawingInfoTest;
import pr2.gameplay.FinishedPageTest;
import pr2.gameplay.HeartsTest;
import pr2.gameplay.StatsDisplayTest;
import pr2.gameplay.CountdownTest;
import pr2.gameplay.CourseTimerTest;
import pr2.gameplay.CatCaptchaTest;
import pr2.gameplay.PrizePopupTest;
import pr2.gameplay.SpectatePickerTest;
import pr2.gameplay.SpecialEventTest;
import pr2.gameplay.PlaceArtifactTest;
import pr2.gameplay.LevelConfigTest;
import pr2.gameplay.ModesTest;
import pr2.gameplay.RoguelikeModeTest;
import pr2.graphics.JPEGEncoderCompatTest;
import pr2.gameplay.GameShellMountTest;
import pr2.gameplay.CharacterLifecycleTest;
import pr2.gameplay.LevelEntryStateTest;
import pr2.gameplay.GameCommandShellTest;
import pr2.gameplay.QuitButtonTest;
import pr2.gameplay.RaceSessionTranscriptTest;
import pr2.level.LevelFixtureParserTest;
import pr2.lobby.LobbyServicesTest;
import pr2.lobby.AccountTabTest;
import pr2.lobby.ArtifactHintClientTest;
import pr2.lobby.AutoDismissPopupTest;
import pr2.lobby.ChatTabTest;
import pr2.lobby.ChangePasswordPopupTest;
import pr2.lobby.ColorPickerTest;
import pr2.lobby.CreateGuildPopupTest;
import pr2.lobby.CreditsPopupTest;
import pr2.lobby.DiscordVerificationPopupTest;
import pr2.lobby.ExternalLinkPopupTest;
import pr2.lobby.GuildPopupTest;
import pr2.lobby.GuildJoinPopupTest;
import pr2.lobby.HatsMenuTest;
import pr2.lobby.HtmlNameMakerTest;
import pr2.lobby.ItemMenuTest;
import pr2.lobby.LevelInfoPopupTest;
import pr2.lobby.LobbySessionTest;
import pr2.lobby.LogoutPassPopupTest;
import pr2.lobby.MessagesItemTest;
import pr2.lobby.OptionsPopupTest;
import pr2.lobby.OutfitPopupTest;
import pr2.lobby.PMRFCodesPopupTest;
import pr2.lobby.PlayerPopupTest;
import pr2.lobby.SendMessagePopupTest;
import pr2.lobby.SetEmailPopupTest;
import pr2.lobby.StorePopupTest;
import pr2.lobby.TransferGuildPopupTest;
import pr2.lobby.UploadingPopupTest;
import pr2.level.ServerLevelDecoderTest;
import pr2.level.ServerLevelFixtureAdapterTest;
import pr2.level.ServerLevelRendererTest;
import pr2.gameplay.CameraFollowTest;
import pr2.net.AccountCreationClientTest;
import pr2.net.ForgotPasswordClientTest;
import pr2.net.CampaignListClientTest;
import pr2.net.CommAuthTest;
import pr2.net.LevelDataClientTest;
import pr2.net.JsonClientTest;
import pr2.net.LoginAuthClientTest;
import pr2.net.LoginSocketProtocolTest;
import pr2.net.LobbySocketLifecycleTest;
import pr2.net.LoginSessionGateTest;
import pr2.net.SavedAccountsTest;
import pr2.net.ServerConfigTest;
import pr2.net.ServerStatusClientTest;
import pr2.net.SuperLoaderTest;
import pr2.page.EditorBlockOptionsTest;
import pr2.page.EditorSettingsTest;
import pr2.page.CampaignTestScreenTest;
import pr2.runtime.FlButtonTest;
import pr2.runtime.FlComponentsTest;
import pr2.runtime.EpicFlashTest;
import pr2.runtime.PR2MovieClipRuntimeTest;
import pr2.runtime.StaticSubtreeAnalyzerTest;
import pr2.runtime.FlattenSafetyGateTest;
import pr2.ui.EmblemLoaderTest;
import pr2.ui.GuildNameTest;
import pr2.ui.GpNotificationTest;
import pr2.ui.PageNavigationFocusTest;
import pr2.ui.SelectableButtonTest;
import pr2.util.AsyncRemovalGuardTest;

class DeterministicTestSuite {
	public static function main():Void {
		AudioUnlockGateTest.main();
		AudioRuntimeTest.main();
		FatalErrorReporterTest.main();
		ScreenTest.main();
		PR2MovieClipRuntimeTest.main();
		StaticSubtreeAnalyzerTest.main();
		FlattenSafetyGateTest.main();
		FlButtonTest.main();
		FlComponentsTest.main();
		EpicFlashTest.main();
		GpNotificationTest.main();
		EmblemLoaderTest.main();
		GuildNameTest.main();
		SelectableButtonTest.main();
		PageNavigationFocusTest.main();
		AsyncRemovalGuardTest.main();
		RemovableTest.main();
		PixelEffect1Test.main();
		PhysicsEffectTest.main();
		ShotEffectTest.main();
		SlashTest.main();
		TeleportPopTest.main();
		CharacterAtlasTest.main();
		CharacterBaseTest.main();
		CharacterDisplayTest.main();
		CharacterStateTest.main();
		LocalCharacterTest.main();
		LocalCharacterEmitTest.main();
		ParticleEmitterTest.main();
		RemoteCharacterConsumeTest.main();
		PR2EncryptorTest.main();
		MD5CompatTest.main();
		ARC4CompatTest.main();
		RandomCompatTest.main();
		HurlantSymmetricCompatTest.main();
		HurlantUtilCompatTest.main();
		DataCompatTest.main();
		JiggminRandomCompatTest.main();
		ObjectsCompatTest.main();
		SecureDataCompatTest.main();
		SettingsCompatTest.main();
		SWFStatsTest.main();
		TimeCompatTest.main();
		LevelFixtureParserTest.main();
		ServerLevelDecoderTest.main();
		ServerLevelFixtureAdapterTest.main();
		ServerLevelRendererTest.main();
		CameraFollowTest.main();
		PlayerDisplayPlacementTest.main();
		LocalPlayerControllerTest.main();
		RotationMathTest.main();
		MiniMapTest.main();
		ItemDisplayTest.main();
		MusicSelectionTest.main();
		RaceChatTest.main();
		DrawingInfoTest.main();
		FinishedPageTest.main();
		HeartsTest.main();
		StatsDisplayTest.main();
		CountdownTest.main();
		CourseTimerTest.main();
		CatCaptchaTest.main();
		PrizePopupTest.main();
		SpectatePickerTest.main();
		SpecialEventTest.main();
		PlaceArtifactTest.main();
		ModesTest.main();
		RoguelikeModeTest.main();
		JPEGEncoderCompatTest.main();
		LevelConfigTest.main();
		GameShellMountTest.main();
		CharacterLifecycleTest.main();
		LevelEntryStateTest.main();
		GameCommandShellTest.main();
		QuitButtonTest.main();
		RaceSessionTranscriptTest.main();
		ServerConfigTest.main();
		CommAuthTest.main();
		ServerStatusClientTest.main();
		LoginSocketProtocolTest.main();
		LobbySocketLifecycleTest.main();
		LoginSessionGateTest.main();
		SavedAccountsTest.main();
		SuperLoaderTest.main();
		CampaignListClientTest.main();
		AccountCreationClientTest.main();
		ForgotPasswordClientTest.main();
		LoginAuthClientTest.main();
		LevelDataClientTest.main();
		JsonClientTest.main();
		EditorBlockOptionsTest.main();
		EditorSettingsTest.main();
		CampaignTestScreenTest.main();
		ArtifactHintClientTest.main();
		AutoDismissPopupTest.main();
		LobbySessionTest.main();
		LobbyServicesTest.main();
		AccountTabTest.main();
		ChatTabTest.main();
		ChangePasswordPopupTest.main();
		ColorPickerTest.main();
		CreateGuildPopupTest.main();
		CreditsPopupTest.main();
		DiscordVerificationPopupTest.main();
		ExternalLinkPopupTest.main();
		GuildPopupTest.main();
		GuildJoinPopupTest.main();
		HatsMenuTest.main();
		HtmlNameMakerTest.main();
		ItemMenuTest.main();
		LevelInfoPopupTest.main();
		LogoutPassPopupTest.main();
		MessagesItemTest.main();
		OptionsPopupTest.main();
		OutfitPopupTest.main();
		PMRFCodesPopupTest.main();
		PlayerPopupTest.main();
		SendMessagePopupTest.main();
		SetEmailPopupTest.main();
		StorePopupTest.main();
		TransferGuildPopupTest.main();
		UploadingPopupTest.main();
		trace("DeterministicTestSuite passed");
		// All assertions are synchronous, but pulling in openfl/lime leaves the
		// eval event loop alive, so the `--interp` process would otherwise hang
		// after main() returns instead of exiting. Terminate explicitly.
		Sys.exit(0);
	}
}
