package pr2;

import pr2.audio.AudioUnlockGateTest;
import pr2.audio.AudioRuntimeTest;
import pr2.app.ScreenTest;
import pr2.character.CharacterAtlasTest;
import pr2.character.CharacterBaseTest;
import pr2.character.CharacterDisplayTest;
import pr2.character.CharacterStateTest;
import pr2.character.LocalCharacterEmitTest;
import pr2.character.LocalCharacterTest;
import pr2.character.RemoteCharacterConsumeTest;
import pr2.crypto.PR2EncryptorTest;
import pr2.effects.PixelEffect1Test;
import pr2.harness.LocalPlayerControllerTest;
import pr2.harness.PlayerDisplayPlacementTest;
import pr2.gameplay.RotationMathTest;
import pr2.gameplay.MiniMapTest;
import pr2.gameplay.ItemDisplayTest;
import pr2.gameplay.MusicSelectionTest;
import pr2.gameplay.RaceChatTest;
import pr2.gameplay.DrawingInfoTest;
import pr2.gameplay.FinishedPageTest;
import pr2.gameplay.HeartsTest;
import pr2.gameplay.StatsDisplayTest;
import pr2.gameplay.CountdownTest;
import pr2.gameplay.CatCaptchaTest;
import pr2.gameplay.PrizePopupTest;
import pr2.gameplay.SpectatePickerTest;
import pr2.gameplay.SpecialEventTest;
import pr2.gameplay.PlaceArtifactTest;
import pr2.gameplay.LevelConfigTest;
import pr2.gameplay.ModesTest;
import pr2.gameplay.GameShellMountTest;
import pr2.gameplay.CharacterLifecycleTest;
import pr2.gameplay.LevelEntryStateTest;
import pr2.gameplay.GameCommandShellTest;
import pr2.gameplay.QuitButtonTest;
import pr2.gameplay.RaceSessionTranscriptTest;
import pr2.level.LevelFixtureParserTest;
import pr2.lobby.LobbyServicesTest;
import pr2.lobby.AccountTabTest;
import pr2.lobby.CreditsPopupTest;
import pr2.lobby.ExternalLinkPopupTest;
import pr2.lobby.GuildPopupTest;
import pr2.lobby.LevelInfoPopupTest;
import pr2.lobby.OptionsPopupTest;
import pr2.lobby.PlayerPopupTest;
import pr2.lobby.SendMessagePopupTest;
import pr2.lobby.StorePopupTest;
import pr2.level.ServerLevelDecoderTest;
import pr2.level.ServerLevelFixtureAdapterTest;
import pr2.level.ServerLevelRendererTest;
import pr2.gameplay.CameraFollowTest;
import pr2.net.AccountCreationClientTest;
import pr2.net.ForgotPasswordClientTest;
import pr2.net.CampaignListClientTest;
import pr2.net.LevelDataClientTest;
import pr2.net.JsonClientTest;
import pr2.net.LoginAuthClientTest;
import pr2.net.LoginSocketProtocolTest;
import pr2.net.LoginSessionGateTest;
import pr2.net.SavedAccountsTest;
import pr2.net.ServerConfigTest;
import pr2.net.ServerStatusClientTest;
import pr2.page.CampaignTestScreenTest;
import pr2.runtime.FlButtonTest;
import pr2.runtime.FlComponentsTest;
import pr2.runtime.PR2MovieClipRuntimeTest;
import pr2.runtime.StaticSubtreeAnalyzerTest;
import pr2.runtime.FlattenSafetyGateTest;
import pr2.tools.SourceClassCoverageInventoryTest;

class DeterministicTestSuite {
	public static function main():Void {
		AudioUnlockGateTest.main();
		AudioRuntimeTest.main();
		ScreenTest.main();
		PR2MovieClipRuntimeTest.main();
		StaticSubtreeAnalyzerTest.main();
		FlattenSafetyGateTest.main();
		SourceClassCoverageInventoryTest.main();
		FlButtonTest.main();
		FlComponentsTest.main();
		PixelEffect1Test.main();
		CharacterAtlasTest.main();
		CharacterBaseTest.main();
		CharacterDisplayTest.main();
		CharacterStateTest.main();
		LocalCharacterTest.main();
		LocalCharacterEmitTest.main();
		RemoteCharacterConsumeTest.main();
		PR2EncryptorTest.main();
		LevelFixtureParserTest.main();
		ServerLevelDecoderTest.main();
		ServerLevelFixtureAdapterTest.main();
		ServerLevelRendererTest.main();
		CameraFollowTest.main();
		PlayerDisplayPlacementTest.main();
		LocalPlayerControllerTest.main();
		RotationMathTest.main();
		MiniMapTest.main();
		ItemDisplayTest.main();
		MusicSelectionTest.main();
		RaceChatTest.main();
		DrawingInfoTest.main();
		FinishedPageTest.main();
		HeartsTest.main();
		StatsDisplayTest.main();
		CountdownTest.main();
		CatCaptchaTest.main();
		PrizePopupTest.main();
		SpectatePickerTest.main();
		SpecialEventTest.main();
		PlaceArtifactTest.main();
		ModesTest.main();
		LevelConfigTest.main();
		GameShellMountTest.main();
		CharacterLifecycleTest.main();
		LevelEntryStateTest.main();
		GameCommandShellTest.main();
		QuitButtonTest.main();
		RaceSessionTranscriptTest.main();
		ServerConfigTest.main();
		ServerStatusClientTest.main();
		LoginSocketProtocolTest.main();
		LoginSessionGateTest.main();
		SavedAccountsTest.main();
		CampaignListClientTest.main();
		AccountCreationClientTest.main();
		ForgotPasswordClientTest.main();
		LoginAuthClientTest.main();
		LevelDataClientTest.main();
		JsonClientTest.main();
		CampaignTestScreenTest.main();
		LobbyServicesTest.main();
		AccountTabTest.main();
		CreditsPopupTest.main();
		ExternalLinkPopupTest.main();
		GuildPopupTest.main();
		LevelInfoPopupTest.main();
		OptionsPopupTest.main();
		PlayerPopupTest.main();
		SendMessagePopupTest.main();
		StorePopupTest.main();
		trace("DeterministicTestSuite passed");
		// All assertions are synchronous, but pulling in openfl/lime leaves the
		// eval event loop alive, so the `--interp` process would otherwise hang
		// after main() returns instead of exiting. Terminate explicitly.
		Sys.exit(0);
	}
}
